import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Chaos Chess Privacy Policy",
  description: "How FireChess handles data when you play the Chaos Chess Discord Activity.",
  alternates: { canonical: "https://firechess.com/chaos/privacy" },
};

export default function ChaosPrivacyPage() {
  return (
    <article className="mx-auto max-w-3xl px-6 py-16 text-sm leading-relaxed text-slate-300 [&_h2]:mb-3 [&_h2]:text-lg [&_h2]:font-bold [&_h2]:text-white [&_section]:mt-8 [&_a]:text-emerald-400 [&_a]:underline">
      <p className="mb-3 text-emerald-400">FireChess · Discord Activity</p>
      <h1 className="text-3xl font-extrabold text-white">Chaos Chess Privacy Policy</h1>
      <p className="mt-3">Effective September 6, 2026</p>
      <section><h2>Scope and operator</h2><p>FireChess operates Chaos Chess, a chess variant playable inside Discord. This policy covers the Discord Activity and its game services. The separate <Link href="/privacy">FireChess website privacy policy</Link> applies to website accounts, analysis tools and subscriptions. Visiting these policy pages also uses the FireChess website, which includes Vercel Web Analytics.</p></section>
      <section><h2>Data used by the Activity</h2><p>The current Activity plays as a guest. It generates a guest identifier on your device and sends it to our game service to identify your seat in a match. Multiplayer data includes room identifiers and join codes, player identifiers and colors, board positions, moves, selected powers, time controls, match status and results. These are processed by our game servers and may be stored in our database. Connection identifiers and presence information are used to synchronize play.</p><p className="mt-3">Discord supplies launch context, such as application, frame, instance, channel or server identifiers, to its embedded SDK. We use the SDK to initialize the Activity. The current version does not request Discord OAuth access to your profile or email, link your Discord identity to a FireChess account, or read your messages, contacts, microphone or camera.</p></section>
      <section><h2>Device storage and technical information</h2><p>Local storage retains the guest identifier, sound and board preferences, AI difficulty and power-preview/progression settings until you clear the relevant site data. Hosting, database, network and content-delivery services may process request metadata, timestamps, errors, browser information and IP addresses for delivery, security and troubleshooting. When Discord proxies requests, our service may receive proxy connection information instead of your device address.</p></section>
      <section><h2>Why we use data and who receives it</h2><p>We use this information to run matches, reconnect players, synchronize turns, remember settings, investigate bugs and prevent misuse. Other people connected to your room receive shared gameplay and presence information; treat room codes as invitations. Infrastructure providers process data needed to deliver the game, including hosting/database services, Cloudflare and the services delivering game assets. Discord separately processes your use of its platform under its <a href="https://discord.com/privacy">Privacy Policy</a>. We do not sell Activity personal data or use Discord API data for targeted advertising.</p></section>
      <section><h2>Retention and deletion</h2><p>Closing the Activity does not automatically delete database records for your matches. The current version has no fixed automatic deletion interval for those records. We retain them for operating the game, troubleshooting and security, and delete or de-identify data when it is no longer needed, subject to legal obligations. Infrastructure logs and backups may remain under the relevant provider&apos;s retention processes.</p><p className="mt-3">You can clear local preferences and your guest identifier by clearing the Activity&apos;s site data. This does not delete server records and may prevent us from identifying them later. To request access, correction or deletion, contact us before clearing that data where possible, providing a room code and approximate match time. We may ask for enough information to confirm the request concerns your data. Do not send passwords, Discord tokens or identity documents.</p></section>
      <section><h2>Your choices and support</h2><p>You may stop using the Activity at any time. Depending on your location, you may have additional rights to access, correct, delete, restrict or object to processing of your personal data, or complain to your local privacy authority. Send privacy requests or report problems through <Link href="/feedback">FireChess support</Link> or the support channel in our <a href="https://discord.gg/YS8fc4FtEk">FireChess Discord server</a>. Ask for a private support conversation before sharing personal details. Service providers may process information outside your country.</p></section>
      <section><h2>Age requirements and changes</h2><p>The Activity is not intended for children under 13 or below Discord&apos;s minimum age in their country, if higher. Contact us if you believe we have collected data from someone below that age. We will update this page when our data practices change and provide an appropriate notice for material changes.</p></section>
      <nav className="mt-10 border-t border-white/10 pt-6"><Link href="/chaos/terms">Chaos Chess Terms of Service</Link> · <Link href="/">FireChess home</Link></nav>
    </article>
  );
}
