/**
 * Daily Chess Tips & Quotes — 365+ entries that rotate by day of year.
 *
 * Categories:
 *  - quote:   Famous chess quotes
 *  - tip:     Practical improvement tips
 *  - fact:    Historical or statistical facts
 *  - pattern: Tactical or positional patterns
 */

export type DailyTip = {
  id: number;
  type: "quote" | "tip" | "fact" | "pattern";
  text: string;
  author?: string;
  category?: string;
};

export const DAILY_TIPS: DailyTip[] = [
  // ──────────────────────────────────────────────────────────────────
  //  QUOTES (1–100)
  // ──────────────────────────────────────────────────────────────────
  { id: 1, type: "quote", text: "Chess is the gymnasium of the mind.", author: "Blaise Pascal" },
  { id: 2, type: "quote", text: "Every chess master was once a beginner.", author: "Irving Chernev" },
  { id: 3, type: "quote", text: "When you see a good move, look for a better one.", author: "Emanuel Lasker" },
  { id: 4, type: "quote", text: "The beauty of chess is it can be whatever you want it to be.", author: "Simon Williams" },
  { id: 5, type: "quote", text: "Tactics flow from a superior position.", author: "Bobby Fischer" },
  { id: 6, type: "quote", text: "Chess is life in miniature.", author: "Garry Kasparov" },
  { id: 7, type: "quote", text: "In chess, as in life, forethought wins.", author: "Charles Buxton" },
  { id: 8, type: "quote", text: "You may learn much more from a game you lose than from a game you win.", author: "José Raúl Capablanca" },
  { id: 9, type: "quote", text: "Chess demands total concentration and a love for the game.", author: "Bobby Fischer" },
  { id: 10, type: "quote", text: "The pin is mightier than the sword.", author: "Fred Reinfeld" },
  { id: 11, type: "quote", text: "Chess is a war over the board. The object is to crush the opponent's mind.", author: "Bobby Fischer" },
  { id: 12, type: "quote", text: "I don't believe in psychology. I believe in good moves.", author: "Bobby Fischer" },
  { id: 13, type: "quote", text: "One bad move nullifies forty good ones.", author: "Bernhard Horwitz" },
  { id: 14, type: "quote", text: "Pawns are the soul of chess.", author: "François-André Philidor" },
  { id: 15, type: "quote", text: "The threat is stronger than the execution.", author: "Aron Nimzowitsch" },
  { id: 16, type: "quote", text: "Chess is not for the faint-hearted; it absorbs a person entirely.", author: "Vladimir Putin" },
  { id: 17, type: "quote", text: "To avoid losing a piece, many a person has lost the game.", author: "Savielly Tartakower" },
  { id: 18, type: "quote", text: "A bad plan is better than no plan at all.", author: "Mikhail Chigorin" },
  { id: 19, type: "quote", text: "Chess is a matter of delicate judgment, knowing when to punch and when to duck.", author: "Bobby Fischer" },
  { id: 20, type: "quote", text: "The winner of the game is the player who makes the next-to-last mistake.", author: "Savielly Tartakower" },
  { id: 21, type: "quote", text: "It is not enough to be a good player; you must also play well.", author: "Siegbert Tarrasch" },
  { id: 22, type: "quote", text: "Chess makes man wiser and clear-sighted.", author: "Vladimir Putin" },
  { id: 23, type: "quote", text: "In life, as in chess, forethought wins.", author: "Charles Buxton" },
  { id: 24, type: "quote", text: "I see only one move ahead, but it is always the correct one.", author: "José Raúl Capablanca" },
  { id: 25, type: "quote", text: "Some sacrifices are sound; the rest are mine.", author: "Mikhail Tal" },
  { id: 26, type: "quote", text: "You must take your opponent into a deep dark forest where 2+2=5.", author: "Mikhail Tal" },
  { id: 27, type: "quote", text: "Chess is everything: art, science, and sport.", author: "Anatoly Karpov" },
  { id: 28, type: "quote", text: "Not all artists are chess players, but all chess players are artists.", author: "Marcel Duchamp" },
  { id: 29, type: "quote", text: "Nobody ever won a chess game by resigning.", author: "Savielly Tartakower" },
  { id: 30, type: "quote", text: "Play the opening like a book, the middlegame like a magician, and the endgame like a machine.", author: "Rudolf Spielmann" },
  { id: 31, type: "quote", text: "Your body has to be in top condition. Your chess deteriorates as your body does.", author: "Bobby Fischer" },
  { id: 32, type: "quote", text: "A sacrifice is best refuted by accepting it.", author: "Wilhelm Steinitz" },
  { id: 33, type: "quote", text: "The most important feature of the chess position is the activity of the pieces.", author: "Michael Stean" },
  { id: 34, type: "quote", text: "Methodical thinking is of more use in chess than inspiration.", author: "C.J.S. Purdy" },
  { id: 35, type: "quote", text: "Help your pieces so they can help you.", author: "Paul Morphy" },
  { id: 36, type: "quote", text: "Chess is imagination.", author: "David Bronstein" },
  { id: 37, type: "quote", text: "Modern chess is too much concerned with things like pawn structure. Forget it — checkmate ends the game.", author: "Nigel Short" },
  { id: 38, type: "quote", text: "Avoid the crowd. Do your own thinking independently.", author: "Bobby Fischer" },
  { id: 39, type: "quote", text: "Chess holds its master in its own bonds, shackling the mind and brain.", author: "Albert Einstein" },
  { id: 40, type: "quote", text: "The passed pawn is a criminal that must be kept under lock and key.", author: "Aron Nimzowitsch" },
  { id: 41, type: "quote", text: "Discovered check is the dive bomb of the chessboard.", author: "Reuben Fine" },
  { id: 42, type: "quote", text: "Of chess it has been said that life is not long enough for it, but that is the fault of life, not chess.", author: "William Napier" },
  { id: 43, type: "quote", text: "When your opponent is struggling, don't make it easier for them.", author: "Garry Kasparov" },
  { id: 44, type: "quote", text: "A strong memory, concentration, imagination, and a strong will are needed to become a great chess player.", author: "Bobby Fischer" },
  { id: 45, type: "quote", text: "It's always better to sacrifice your opponent's men.", author: "Savielly Tartakower" },
  { id: 46, type: "quote", text: "On the chessboard, lies and hypocrisy do not survive long.", author: "Emanuel Lasker" },
  { id: 47, type: "quote", text: "Chess is a forcing house where the weights of the important character traits can be tested.", author: "Emanuel Lasker" },
  { id: 48, type: "quote", text: "Life is a kind of chess, with struggle, competition, good and ill events.", author: "Benjamin Franklin" },
  { id: 49, type: "quote", text: "A chess game is divided into three stages: the first, when you hope you have the advantage; the second, when you believe you have an advantage; and the third, when you know you're going to lose.", author: "Savielly Tartakower" },
  { id: 50, type: "quote", text: "In blitz, the weights of the pieces change. Bishops become stronger, knights become weaker.", author: "Viswanathan Anand" },
  { id: 51, type: "quote", text: "Strategy requires thought; tactics require observation.", author: "Max Euwe" },
  { id: 52, type: "quote", text: "I have never in my life played the French Defense, which is the dullest of all openings.", author: "Wilhelm Steinitz" },
  { id: 53, type: "quote", text: "There are two types of sacrifices: correct ones, and mine.", author: "Mikhail Tal" },
  { id: 54, type: "quote", text: "Chess is mental torture.", author: "Garry Kasparov" },
  { id: 55, type: "quote", text: "A player surprised is half beaten.", author: "Chess proverb" },
  { id: 56, type: "quote", text: "The chessboard is the world, the pieces are the phenomena of the Universe.", author: "Thomas Huxley" },
  { id: 57, type: "quote", text: "Openings teach you openings. Endgames teach you chess.", author: "Stephan Gerzadowicz" },
  { id: 58, type: "quote", text: "In chess, the only thing worse than getting beaten is not having a plan.", author: "Chess proverb" },
  { id: 59, type: "quote", text: "Excellence at chess is one mark of a scheming mind.", author: "Arthur Conan Doyle" },
  { id: 60, type: "quote", text: "If your opponent offers you a draw, try to work out why he thinks he's worse.", author: "Nigel Short" },
  { id: 61, type: "quote", text: "The hardest game to win is a won game.", author: "Emanuel Lasker" },
  { id: 62, type: "quote", text: "Without error there can be no brilliancy.", author: "Emanuel Lasker" },
  { id: 63, type: "quote", text: "Half the variations calculated in a tournament game turn out to be completely superfluous.", author: "Jan Hein Donner" },
  { id: 64, type: "quote", text: "Chess is struggle, chess is battles.", author: "Garry Kasparov" },
  { id: 65, type: "quote", text: "I used to attack because it was the only thing I knew. Now I attack because I know it works.", author: "Garry Kasparov" },
  { id: 66, type: "quote", text: "Good players develop a sense for the key moments in a game.", author: "Magnus Carlsen" },
  { id: 67, type: "quote", text: "Confidence is very important — even pretending to be confident.", author: "Magnus Carlsen" },
  { id: 68, type: "quote", text: "Chess will always be in my heart.", author: "Magnus Carlsen" },
  { id: 69, type: "quote", text: "The most powerful weapon in chess is to have the next move.", author: "David Bronstein" },
  { id: 70, type: "quote", text: "A chess game in progress is… a cosmos unto itself, fully insulated from an objective description of Reality.", author: "Turing Award" },
  { id: 71, type: "quote", text: "All I want to do, ever, is play chess.", author: "Bobby Fischer" },
  { id: 72, type: "quote", text: "We like to think.", author: "Garry Kasparov" },
  { id: 73, type: "quote", text: "I always urge players to study composed problems and endgames.", author: "Pal Benko" },
  { id: 74, type: "quote", text: "The most important thing in chess is the pawn structure.", author: "Tigran Petrosian" },
  { id: 75, type: "quote", text: "Good positions don't win games. Good moves do.", author: "Gerald Abrahams" },
  { id: 76, type: "quote", text: "You can only get good at chess if you love the game.", author: "Bobby Fischer" },
  { id: 77, type: "quote", text: "If I win a tournament, I win it by myself. I do well because I play well.", author: "Magnus Carlsen" },
  { id: 78, type: "quote", text: "I am convinced, the way one plays chess always reflects the player's personality.", author: "Vladimir Kramnik" },
  { id: 79, type: "quote", text: "In order to improve your game, you must study the endgame before everything else.", author: "José Raúl Capablanca" },
  { id: 80, type: "quote", text: "Chess is in its essence a game, in its form an art, and in its execution a science.", author: "Baron Tassilo" },
  { id: 81, type: "quote", text: "Those who say they understand chess, understand nothing.", author: "Robert Hübner" },
  { id: 82, type: "quote", text: "I believe in hard work. One gains nothing without effort.", author: "Philip Robar" },
  { id: 83, type: "quote", text: "All that matters on the chessboard is good moves.", author: "Bobby Fischer" },
  { id: 84, type: "quote", text: "Place the contents of your opponent's game ahead of your own.", author: "Siegbert Tarrasch" },
  { id: 85, type: "quote", text: "We cannot resist the fascination of sacrifice, since a passion for sacrifices is part of a chess player's nature.", author: "Rudolf Spielmann" },
  { id: 86, type: "quote", text: "My style is somewhere between that of Tal and Petrosian.", author: "Tigran Petrosian" },
  { id: 87, type: "quote", text: "An isolated pawn spreads gloom all over the chessboard.", author: "Savielly Tartakower" },
  { id: 88, type: "quote", text: "Pawn endings are to chess what putting is to golf.", author: "Cecil Purdy" },
  { id: 89, type: "quote", text: "First-class players lose to second-class players because second-class players sometimes play a first-class game.", author: "Siegbert Tarrasch" },
  { id: 90, type: "quote", text: "Chess is so inspiring that I do not believe a good player is capable of having an evil thought during the game.", author: "Wilhelm Steinitz" },

  // ──────────────────────────────────────────────────────────────────
  //  TIPS (91–230)
  // ──────────────────────────────────────────────────────────────────
  { id: 91, type: "tip", text: "Develop all your pieces before launching an attack. Knights and bishops should be off the back rank by move 10.", category: "opening" },
  { id: 92, type: "tip", text: "Castle early. Leaving your king in the center invites tactical shots and discovered attacks.", category: "opening" },
  { id: 93, type: "tip", text: "Don't move the same piece twice in the opening unless there's a concrete reason (threat, winning material).", category: "opening" },
  { id: 94, type: "tip", text: "Control the center with pawns (e4/d4) or pieces. Central pieces have more squares to go to.", category: "opening" },
  { id: 95, type: "tip", text: "Connect your rooks by developing all minor pieces first. Rooks are strongest on open files.", category: "middlegame" },
  { id: 96, type: "tip", text: "Before every move, ask: what is my opponent threatening? This one habit will save you hundreds of rating points.", category: "general" },
  { id: 97, type: "tip", text: "When ahead in material, trade pieces, not pawns. When behind, trade pawns, not pieces.", category: "endgame" },
  { id: 98, type: "tip", text: "Place your rooks on open or semi-open files. A rook on a closed file is just a tall pawn.", category: "middlegame" },
  { id: 99, type: "tip", text: "Knights are best in closed positions with locked pawn chains. Bishops are best in open positions.", category: "middlegame" },
  { id: 100, type: "tip", text: "In the endgame, activate your king! It becomes a fighting piece worth roughly 4 points.", category: "endgame" },
  { id: 101, type: "tip", text: "Never play a move you do not understand. If you can't explain why, you shouldn't play it.", category: "general" },
  { id: 102, type: "tip", text: "Study one opening system in depth rather than skimming many. A player who knows their opening has a huge practical advantage.", category: "opening" },
  { id: 103, type: "tip", text: "Use the 'Checks, Captures, Threats' method: always consider these forcing moves first when calculating.", category: "tactics" },
  { id: 104, type: "tip", text: "A knight on the rim is dim. Avoid placing knights on edge squares (a/h files) unless there's a specific reason.", category: "middlegame" },
  { id: 105, type: "tip", text: "After your opponent's move, ask: what changed? What squares are weak now? What piece is undefended?", category: "general" },
  { id: 106, type: "tip", text: "Don't bring your queen out too early. It becomes a target, losing tempi to enemy piece development.", category: "opening" },
  { id: 107, type: "tip", text: "If your opponent has an isolated queen pawn, blockade it with a knight on d5 (or d4 as Black).", category: "middlegame" },
  { id: 108, type: "tip", text: "Doubled pawns aren't always bad — they can open files for rooks and control key squares.", category: "middlegame" },
  { id: 109, type: "tip", text: "A passed pawn must be pushed! In the endgame, advancing a passed pawn creates winning chances.", category: "endgame" },
  { id: 110, type: "tip", text: "In rook endgames, place your rook behind passed pawns — both yours and your opponent's.", category: "endgame" },
  { id: 111, type: "tip", text: "When you're in time trouble, make safe, solid moves rather than complex calculations.", category: "general" },
  { id: 112, type: "tip", text: "Always have a plan. Even a bad plan is better than no plan. Ask: what do I want to achieve?", category: "middlegame" },
  { id: 113, type: "tip", text: "The two bishops (bishop pair) is a significant advantage in open positions. Try to keep them.", category: "middlegame" },
  { id: 114, type: "tip", text: "After every blunder you make, write it down. Look for patterns — you'll find you repeat the same mistakes.", category: "improvement" },
  { id: 115, type: "tip", text: "Play slower time controls to improve. Blitz reinforces bad habits; classical builds good ones.", category: "improvement" },
  { id: 116, type: "tip", text: "Learn basic checkmate patterns: K+Q vs K, K+R vs K, and K+2B vs K. These are fundamental.", category: "endgame" },
  { id: 117, type: "tip", text: "Don't memorize opening moves — understand the ideas behind them. Plans transfer better than move orders.", category: "opening" },
  { id: 118, type: "tip", text: "A fianchettoed bishop (on g2/b2 or g7/b7) is a powerful piece. Don't trade it without good reason.", category: "middlegame" },
  { id: 119, type: "tip", text: "Looking at the pawn structure tells you the plan. Pawn breaks, weaknesses, and outposts all come from pawns.", category: "middlegame" },
  { id: 120, type: "tip", text: "If you're attacking and your opponent is defending, avoid trades. Each trade reduces your attacking potential.", category: "tactics" },
  { id: 121, type: "tip", text: "Solve 10-15 tactics puzzles per day consistently. Short daily practice beats marathon sessions.", category: "improvement" },
  { id: 122, type: "tip", text: "In king and pawn endgames, opposition is key. The player who achieves opposition controls the outcome.", category: "endgame" },
  { id: 123, type: "tip", text: "When defending, exchange attacking pieces but keep defenders. Reducing the opponent's forces makes survival easier.", category: "middlegame" },
  { id: 124, type: "tip", text: "A piece that is doing nothing is worth nothing. Always ask: is this piece actively contributing?", category: "middlegame" },
  { id: 125, type: "tip", text: "Study your losses more than your wins. Losses reveal your weaknesses; wins mostly confirm what you already know.", category: "improvement" },
  { id: 126, type: "tip", text: "Don't be afraid of gambits. Understanding whether to accept or decline teaches deep chess principles.", category: "opening" },
  { id: 127, type: "tip", text: "Create a repertoire for both colors. Consistency in openings builds pattern recognition over hundreds of games.", category: "opening" },
  { id: 128, type: "tip", text: "In opposite-color bishop endgames, the attacker has an advantage because the defender can't trade bishops.", category: "endgame" },
  { id: 129, type: "tip", text: "The Lucena position (rook endgame) is the most important endgame position to learn. Build a bridge!", category: "endgame" },
  { id: 130, type: "tip", text: "The Philidor position (rook endgame) is the second most important: keep your rook on the 6th rank to draw.", category: "endgame" },
  { id: 131, type: "tip", text: "Always check if a knight fork exists when pieces are on the same color squares near each other.", category: "tactics" },
  { id: 132, type: "tip", text: "Look for back-rank weaknesses — if the king is trapped on the first rank, tactical shots may appear.", category: "tactics" },
  { id: 133, type: "tip", text: "Pins and skewers work on diagonals and files. Scan for pieces lined up on the same line.", category: "tactics" },
  { id: 134, type: "tip", text: "Before sacrificing material, verify the follow-up. A sacrifice without a clear continuation is just losing material.", category: "tactics" },
  { id: 135, type: "tip", text: "Use prophylaxis — prevent your opponent's best plan before executing your own.", category: "middlegame" },
  { id: 136, type: "tip", text: "When up an exchange (rook vs minor piece), open the position to let the rook dominate on open files.", category: "middlegame" },
  { id: 137, type: "tip", text: "Don't grab pawns in the opening if it means falling behind in development. Time is worth more than a pawn.", category: "opening" },
  { id: 138, type: "tip", text: "Learn to play with and against isolated queen pawns. It's one of the most common structures in chess.", category: "middlegame" },
  { id: 139, type: "tip", text: "After a game, don't just check the computer evaluation. Ask why your move was wrong and what principle you violated.", category: "improvement" },
  { id: 140, type: "tip", text: "In the Sicilian, Black's main break is …d5. In the French, it's …c5. Know your pawn breaks!", category: "opening" },
  { id: 141, type: "tip", text: "A centralized knight on an outpost (protected by a pawn, can't be kicked) is worth almost as much as a rook.", category: "middlegame" },
  { id: 142, type: "tip", text: "Don't rush. Before making a move, take one more look at the whole board. Fresh eyes catch blunders.", category: "general" },
  { id: 143, type: "tip", text: "When calculating forced sequences, count the moves for both sides. If you're faster, you're probably winning.", category: "tactics" },
  { id: 144, type: "tip", text: "Zwischenzug (in-between move) — before recapturing, check if there's a stronger intermediate move.", category: "tactics" },
  { id: 145, type: "tip", text: "In pawn endgames, count tempi carefully. One extra move often decides the game.", category: "endgame" },
  { id: 146, type: "tip", text: "The principle of two weaknesses: attack on both sides of the board. The defender can't cover everything.", category: "middlegame" },
  { id: 147, type: "tip", text: "A good motto: improve your worst piece. Find which piece is doing the least and reroute it.", category: "middlegame" },
  { id: 148, type: "tip", text: "Don't play hope chess. If your plan depends on your opponent making a mistake, find a better plan.", category: "general" },
  { id: 149, type: "tip", text: "In queen endgames, centralize your queen and keep checking the opponent's king. Activity is everything.", category: "endgame" },
  { id: 150, type: "tip", text: "When both sides have castled on the same side, pawn storms are risky — you weaken your own king.", category: "middlegame" },
  { id: 151, type: "tip", text: "Analyze your games without an engine first. Form your own opinions, then check with a computer.", category: "improvement" },
  { id: 152, type: "tip", text: "Know when to go for a draw. A half-point is better than zero. Tournament chess is a marathon.", category: "general" },
  { id: 153, type: "tip", text: "In time scrambles, pre-move checks and captures that are clearly winning. Don't think — execute.", category: "general" },
  { id: 154, type: "tip", text: "Bishop vs knight: the bishop is usually better in endgames with pawns on both sides of the board.", category: "endgame" },
  { id: 155, type: "tip", text: "Avoid unnecessary pawn moves in the opening. Each pawn move is a tempo that could develop a piece.", category: "opening" },
  { id: 156, type: "tip", text: "In opposite-side castling, race to attack the opponent's king. He who strikes first usually wins.", category: "middlegame" },
  { id: 157, type: "tip", text: "The exchange sacrifice (rook for minor piece) is a powerful tool. Don't be afraid to give up material for positional compensation.", category: "middlegame" },
  { id: 158, type: "tip", text: "Learn the rule of the square for pawn promotion endgames. If the king is inside the square, it catches the pawn.", category: "endgame" },
  { id: 159, type: "tip", text: "When evaluating a position, check: king safety, material, pawn structure, piece activity, and space.", category: "general" },
  { id: 160, type: "tip", text: "Play through master games — not for memorization, but to absorb typical plans and piece maneuvers.", category: "improvement" },
  { id: 161, type: "tip", text: "If your opponent plays a move you don't understand, be extra careful. They might have seen something you haven't.", category: "general" },
  { id: 162, type: "tip", text: "Backward pawns on open files are weak because they can be attacked by rooks and can't be defended by pawns.", category: "middlegame" },
  { id: 163, type: "tip", text: "The 'desperado' concept: if a piece is lost anyway, grab as much material as possible before it goes.", category: "tactics" },
  { id: 164, type: "tip", text: "In minor piece endgames, the side with the bishop usually prefers to keep pawns on both sides of the board.", category: "endgame" },
  { id: 165, type: "tip", text: "When you have a space advantage, avoid unnecessary trades. Your pieces have more room; keep them.", category: "middlegame" },
  { id: 166, type: "tip", text: "Stalemate is the defender's best friend in endgames. Always consider stalemate tricks when material down.", category: "endgame" },
  { id: 167, type: "tip", text: "The seventh rank is paradise for rooks. A rook on the 7th cuts off the king and attacks pawns from behind.", category: "middlegame" },
  { id: 168, type: "tip", text: "Don't play a different opening every game. Consistency lets you build a deep understanding of the positions.", category: "opening" },
  { id: 169, type: "tip", text: "After the game, note the exact moment where things went wrong — usually it's earlier than you think.", category: "improvement" },
  { id: 170, type: "tip", text: "Simplify when winning. Don't try to find the prettiest checkmate — the safest win is the best win.", category: "general" },
  { id: 171, type: "tip", text: "Weak squares are more important than weak pawns. A weak square can be occupied; a weak pawn can sometimes be defended.", category: "middlegame" },
  { id: 172, type: "tip", text: "When your opponent plays a gambit you're not familiar with, accept it and develop solidly. Don't try to hold the pawn at all costs.", category: "opening" },
  { id: 173, type: "tip", text: "The 50-move rule and threefold repetition are real — know when to claim a draw in dire positions.", category: "endgame" },
  { id: 174, type: "tip", text: "Spend more time on critical moments. Don't use the same time for every move — invest time when it matters.", category: "general" },
  { id: 175, type: "tip", text: "Train pattern recognition by solving puzzles of the same theme (e.g., all pins, all back-rank mates).", category: "improvement" },
  { id: 176, type: "tip", text: "A well-timed h3 or h6 (preventing Bg5/Bg4) can save you from annoying pins on the f3/f6 knight.", category: "opening" },
  { id: 177, type: "tip", text: "When deciding between two captures, check which one leads to a better pawn structure.", category: "middlegame" },
  { id: 178, type: "tip", text: "Interference: placing a piece between two enemy pieces on the same line can break their coordination.", category: "tactics" },
  { id: 179, type: "tip", text: "Deflection: force a defending piece away from its defensive duty to create a tactic.", category: "tactics" },
  { id: 180, type: "tip", text: "Decoy: lure an enemy piece to a vulnerable square where it can be exploited.", category: "tactics" },
  { id: 181, type: "tip", text: "Windmill: an alternating discovered check that wins massive material. Learn to spot the pattern.", category: "tactics" },
  { id: 182, type: "tip", text: "X-ray defense: one piece defends through another piece on the same line. Very useful in endgames.", category: "tactics" },
  { id: 183, type: "tip", text: "Overloading: if one piece defends two things, attack both. Something will drop.", category: "tactics" },
  { id: 184, type: "tip", text: "Zugzwang: in the endgame, the obligation to move can be a disadvantage. Force your opponent into zugzwang.", category: "endgame" },
  { id: 185, type: "tip", text: "Connected passed pawns on the 6th rank are stronger than a rook. Push them together!", category: "endgame" },
  { id: 186, type: "tip", text: "Avoid 'automatic' recaptures. Sometimes taking with the wrong piece or pawn leads to a worse structure.", category: "general" },
  { id: 187, type: "tip", text: "Use the Blumenfeld Rule: in pawn endings, put yourself in your opponent's shoes to find the best defense.", category: "endgame" },
  { id: 188, type: "tip", text: "When analyzing, try to find one or two key moments rather than annotating every single move.", category: "improvement" },
  { id: 189, type: "tip", text: "In a symmetrical position, the player with the initiative usually has the advantage. Be active!", category: "middlegame" },
  { id: 190, type: "tip", text: "Never give up a half-open file without a fight. Semi-open files are highways for rook activity.", category: "middlegame" },
  { id: 191, type: "tip", text: "Minor pieces coordinate best in pairs. A bishop and knight together can create powerful threats.", category: "middlegame" },
  { id: 192, type: "tip", text: "In rapid and blitz, play openings you know cold. Experiments belong in classical or friendly games.", category: "general" },
  { id: 193, type: "tip", text: "When up material, don't be greedy. Safety first — consolidate your position before grabbing more.", category: "general" },
  { id: 194, type: "tip", text: "Active rook vs passive rook is almost worth a pawn. Rook activity is crucial in all phases.", category: "middlegame" },
  { id: 195, type: "tip", text: "Learn the triangulation technique in king and pawn endgames. It helps gain a crucial tempo.", category: "endgame" },
  { id: 196, type: "tip", text: "Color complex: if your opponent has a light-squared bishop, place your pawns on light squares to restrict it.", category: "middlegame" },
  { id: 197, type: "tip", text: "In the Ruy López, the move …a6 is not just attacking the bishop — it prepares …b5 and queenside expansion.", category: "opening" },
  { id: 198, type: "tip", text: "Before playing Bc4 or Bb5, ask: what is this bishop actually doing here? Don't develop on autopilot.", category: "opening" },
  { id: 199, type: "tip", text: "Rook lifts (Rf3-g3 or Rf3-h3) are powerful attacking maneuvers. Think of the rook as a lateral attacker.", category: "middlegame" },
  { id: 200, type: "tip", text: "When defending an inferior position, resist the urge to 'do something.' Sometimes the best defense is patience.", category: "general" },
  { id: 201, type: "tip", text: "Semi-open files (where you have no pawn but your opponent does) are great for rook pressure.", category: "middlegame" },
  { id: 202, type: "tip", text: "Post-mortem analysis: play through your game with your opponent after the game. Both players learn more.", category: "improvement" },
  { id: 203, type: "tip", text: "Queen + Knight coordinate better on attacks than Queen + Bishop, especially around the king.", category: "middlegame" },
  { id: 204, type: "tip", text: "A hanging pawn duo (c4+d4 or c5+d5 without support) can be either a strength or a weakness. Know both sides.", category: "middlegame" },
  { id: 205, type: "tip", text: "In rook vs bishop endgames, the rook usually wins with correct play. Cut off the king and create a passed pawn.", category: "endgame" },
  { id: 206, type: "tip", text: "Double attacks win games. Always look for moves that threaten two things simultaneously.", category: "tactics" },
  { id: 207, type: "tip", text: "In K+P vs K, the key squares (d5, e5 for a d-pawn) tell you if the pawn can promote. Learn them.", category: "endgame" },
  { id: 208, type: "tip", text: "Don't resign too early in online games. Your opponent might blunder, disconnect, or run out of time.", category: "general" },
  { id: 209, type: "tip", text: "The hedgehog structure (pawns on a6, b6, d6, e6) is elastic — it bends but doesn't break.", category: "middlegame" },
  { id: 210, type: "tip", text: "Prophylactic thinking: what is my opponent's ideal move? How can I prevent it?", category: "middlegame" },
  { id: 211, type: "tip", text: "When studying openings, focus on pawn structures and typical piece placements, not just move orders.", category: "improvement" },
  { id: 212, type: "tip", text: "Good bishop = pawns on opposite color. Bad bishop = pawns on the same color as the bishop.", category: "middlegame" },
  { id: 213, type: "tip", text: "Use your clock wisely. Spending 10 minutes on a move is fine if it's the critical moment of the game.", category: "general" },
  { id: 214, type: "tip", text: "In endgames, cut off the opponent's king from the action. A passive king loses nearly every endgame.", category: "endgame" },
  { id: 215, type: "tip", text: "Flank attacks should be met by central counterplay. If your opponent attacks on the wing, strike in the center.", category: "middlegame" },
  { id: 216, type: "tip", text: "Practice blindfold visualization: try to follow a short game in your head without a board.", category: "improvement" },
  { id: 217, type: "tip", text: "In B+N vs K checkmate, drive the king to the corner of the bishop's color. This is a must-know technique.", category: "endgame" },
  { id: 218, type: "tip", text: "Watch grandmaster commentary to understand how top players think about positions.", category: "improvement" },
  { id: 219, type: "tip", text: "Before a tournament game, warm up with a few puzzles. It activates your tactical pattern recognition.", category: "general" },
  { id: 220, type: "tip", text: "When you lose, don't jump into the next game immediately. Take a break, analyze, then play again.", category: "improvement" },
  { id: 221, type: "tip", text: "Don't over-rely on engine analysis. The computer's first choice isn't always humanly playable.", category: "improvement" },
  { id: 222, type: "tip", text: "Typical sacrifice: Bxh7+ (the Greek Gift). Look for it when you have a bishop on d3 and knight on f3.", category: "tactics" },
  { id: 223, type: "tip", text: "The minority attack (b4-b5 when you have a/b pawns vs a/b/c) creates targets on the queenside.", category: "middlegame" },
  { id: 224, type: "tip", text: "Two rooks are generally stronger than a queen in the middlegame, but weaker in endgames.", category: "middlegame" },
  { id: 225, type: "tip", text: "Avoid moving pawns in front of your castled king unless absolutely necessary.", category: "middlegame" },
  { id: 226, type: "tip", text: "When you have a knight, seek closed positions with fixed pawn chains where the knight can outmaneuver a bishop.", category: "middlegame" },
  { id: 227, type: "tip", text: "Every pawn move creates a weakness and a strength. Think about both sides before pushing.", category: "general" },
  { id: 228, type: "tip", text: "Piece coordination > individual piece strength. A coordinated army beats disconnected superstars.", category: "middlegame" },
  { id: 229, type: "tip", text: "In drawn endgames, keep the position steady. Don't be tempted to 'try to win' and lose instead.", category: "endgame" },
  { id: 230, type: "tip", text: "Learn the Tarrasch rule: always place rooks behind passed pawns. This rule applies in almost every case.", category: "endgame" },

  // ──────────────────────────────────────────────────────────────────
  //  FACTS (231–310)
  // ──────────────────────────────────────────────────────────────────
  { id: 231, type: "fact", text: "There are 318,979,564,000 possible ways to play the first four moves of chess.", category: "math" },
  { id: 232, type: "fact", text: "The number of possible chess games is greater than the number of atoms in the observable universe (Shannon number: ~10^120).", category: "math" },
  { id: 233, type: "fact", text: "The longest chess game theoretically possible is 5,949 moves (due to repetition and 50-move rules).", category: "math" },
  { id: 234, type: "fact", text: "The word 'checkmate' comes from the Persian phrase 'Shah Mat,' meaning 'the King is helpless.'", category: "history" },
  { id: 235, type: "fact", text: "The oldest recorded chess game dates from the 900s, played between a historian from Baghdad and a pupil.", category: "history" },
  { id: 236, type: "fact", text: "The first chess computer program was written by Alan Turing in 1951.", category: "history" },
  { id: 237, type: "fact", text: "The shortest possible checkmate is the Fool's Mate: 1.f3 e5 2.g4 Qh4# — just two moves.", category: "trivia" },
  { id: 238, type: "fact", text: "Deep Blue defeated Garry Kasparov in 1997, becoming the first computer to beat a reigning world champion in a match.", category: "history" },
  { id: 239, type: "fact", text: "Magnus Carlsen's peak rating of 2882 (2014) is the highest in chess history.", category: "records" },
  { id: 240, type: "fact", text: "The longest official tournament game lasted 269 moves (Nikolić vs. Arsović, 1989). It was a draw.", category: "records" },
  { id: 241, type: "fact", text: "Chess originated in India around the 6th century as 'Chaturanga' and spread through Persia to the Arab world.", category: "history" },
  { id: 242, type: "fact", text: "The queen used to be the weakest piece (moving only one diagonal square). It became the strongest during the Renaissance.", category: "history" },
  { id: 243, type: "fact", text: "Bobby Fischer's 1972 World Championship match against Spassky was watched by an estimated 40+ million people worldwide.", category: "history" },
  { id: 244, type: "fact", text: "The en passant rule was introduced around the 15th century when the pawn's initial double-step was added.", category: "history" },
  { id: 245, type: "fact", text: "The International Chess Federation (FIDE) was founded on July 20, 1924, in Paris.", category: "history" },
  { id: 246, type: "fact", text: "A knight can reach any square on the board from any other square in at most 6 moves.", category: "math" },
  { id: 247, type: "fact", text: "8 queens can be placed on a standard chessboard so none attacks any other (92 solutions exist).", category: "math" },
  { id: 248, type: "fact", text: "The word 'rook' comes from the Persian word 'rukh,' meaning chariot.", category: "history" },
  { id: 249, type: "fact", text: "The first official World Chess Championship was held in 1886, won by Wilhelm Steinitz.", category: "history" },
  { id: 250, type: "fact", text: "Stockfish, the strongest open-source engine, has an estimated rating over 3600 — about 700 points above elite GMs.", category: "technology" },
  { id: 251, type: "fact", text: "The youngest world champion was Garry Kasparov, who won the title at age 22 in 1985.", category: "records" },
  { id: 252, type: "fact", text: "Sergey Karjakin became the youngest grandmaster ever at age 12 years and 7 months in 2002.", category: "records" },
  { id: 253, type: "fact", text: "Judit Polgár, the strongest female player in history, peaked at #8 in the world rankings.", category: "records" },
  { id: 254, type: "fact", text: "There are only 400 possible positions after each player has made one move.", category: "math" },
  { id: 255, type: "fact", text: "From the starting position, there are exactly 20 possible first moves for White.", category: "math" },
  { id: 256, type: "fact", text: "The Scholar's Mate (1.e4 e5 2.Qh5 Nc6 3.Bc4 Nf6?? 4.Qxf7#) is the fastest checkmate in common use.", category: "trivia" },
  { id: 257, type: "fact", text: "The immortal game (Anderssen vs. Kieseritzky, 1851) is considered one of the most brilliant games ever played.", category: "history" },
  { id: 258, type: "fact", text: "Chess was the first major game where a computer defeated the human world champion.", category: "history" },
  { id: 259, type: "fact", text: "The Marshall Attack in the Ruy López was kept as a surprise weapon for years before being played in 1918.", category: "history" },
  { id: 260, type: "fact", text: "The Elo rating system, invented by Arpad Elo in 1960, is used in chess and many other competitive activities.", category: "history" },
  { id: 261, type: "fact", text: "A chess board has 64 squares: 32 light and 32 dark, always with a light square in each player's right corner.", category: "trivia" },
  { id: 262, type: "fact", text: "Blindfold chess — playing without seeing the board — has been practiced since the Middle Ages.", category: "history" },
  { id: 263, type: "fact", text: "The Opera Game (Morphy vs. Duke of Brunswick, 1858) is considered the most instructive attacking game ever.", category: "history" },
  { id: 264, type: "fact", text: "In competitive chess, players have been caught cheating with hidden earpieces, phones in bathrooms, and even shoe devices.", category: "trivia" },
  { id: 265, type: "fact", text: "The first chess clock was invented in 1883 by Thomas Bright Wilson.", category: "history" },
  { id: 266, type: "fact", text: "AlphaZero, Google's AI, defeated Stockfish 8 in 2017 after only 4 hours of self-training.", category: "technology" },
  { id: 267, type: "fact", text: "Chess is recognized as a sport by the International Olympic Committee.", category: "trivia" },
  { id: 268, type: "fact", text: "The longest world championship game was Karpov vs. Kasparov (1984) — the match lasted 48 games before being called off.", category: "records" },
  { id: 269, type: "fact", text: "India, Russia, and China produce the most grandmasters in the world today.", category: "trivia" },
  { id: 270, type: "fact", text: "Pawn promotion to a piece other than a queen is called underpromotion — knight promotion is most useful (for forks/checks).", category: "trivia" },
  { id: 271, type: "fact", text: "The Sicilian Defense (1…c5) is the most popular response to 1.e4 at the grandmaster level.", category: "statistics" },
  { id: 272, type: "fact", text: "White wins about 55% of decisive games. The first-move advantage is real but slight.", category: "statistics" },
  { id: 273, type: "fact", text: "The average chess rating on Lichess is approximately 1500 (based on the Glicko-2 system).", category: "statistics" },
  { id: 274, type: "fact", text: "A knight tour — visiting all 64 squares exactly once — has been known since at least the 9th century.", category: "math" },
  { id: 275, type: "fact", text: "The Staunton chess set design (1849) is the standard for tournament play worldwide.", category: "history" },
  { id: 276, type: "fact", text: "The term 'grandmaster' was first formally used by Tsar Nicholas II of Russia for the 1914 St. Petersburg tournament.", category: "history" },
  { id: 277, type: "fact", text: "There are 9,132,484 possible positions after 3 moves each. The game tree explodes exponentially.", category: "math" },
  { id: 278, type: "fact", text: "Bobby Fischer patented a modified chess clock with time-increment per move — now standard in most tournaments.", category: "history" },
  { id: 279, type: "fact", text: "The castling rules as we know them were standardized in the 17th century.", category: "history" },
  { id: 280, type: "fact", text: "In 2023, Ding Liren became the 17th undisputed World Chess Champion, succeeding Magnus Carlsen.", category: "history" },
  { id: 281, type: "fact", text: "Mikhail Tal, the 'Magician from Riga,' was famous for his daring sacrifices and imaginative attack play.", category: "history" },
  { id: 282, type: "fact", text: "The average grandmaster game lasts about 40 moves and takes around 4 hours.", category: "statistics" },
  { id: 283, type: "fact", text: "Chess notation (algebraic) was standardized by Philipp Stamma in the 18th century.", category: "history" },
  { id: 284, type: "fact", text: "Online chess has exploded since 2020 — Lichess and Chess.com each see millions of games played daily.", category: "statistics" },
  { id: 285, type: "fact", text: "The Queen's Gambit Netflix series (2020) caused a 500%+ increase in chess set sales worldwide.", category: "trivia" },
  { id: 286, type: "fact", text: "Paul Morphy, considered the first unofficial world champion, retired from chess at age 22.", category: "history" },
  { id: 287, type: "fact", text: "Emanuel Lasker held the world championship for 27 years (1894-1921), the longest reign ever.", category: "records" },
  { id: 288, type: "fact", text: "Pragg (Rameshbabu Praggnanandhaa) became the youngest International Master in 2016 at age 10.", category: "records" },
  { id: 289, type: "fact", text: "Bird's Opening (1.f4) and the Dutch Defense (1.d4 f5) are named after Henry Bird, a 19th-century English master.", category: "history" },
  { id: 290, type: "fact", text: "The Berlin Defense in the Ruy López gained the nickname 'Berlin Wall' for its drawish reputation.", category: "trivia" },
  { id: 291, type: "fact", text: "Chess960 (Fischer Random) uses 960 different starting positions to reduce opening preparation.", category: "trivia" },
  { id: 292, type: "fact", text: "Hikaru Nakamura has been streaming chess since 2020, amassing over 2 million Twitch followers.", category: "trivia" },
  { id: 293, type: "fact", text: "The first women's world championship was held in 1927, won by Vera Menchik.", category: "history" },
  { id: 294, type: "fact", text: "Kasparov vs. Deep Blue (1997) was broadcast worldwide — one of the most-watched intellectual contests in history.", category: "history" },
  { id: 295, type: "fact", text: "Hans Niemann's controversial 2022 win over Magnus Carlsen sparked the biggest cheating debate in chess history.", category: "trivia" },
  { id: 296, type: "fact", text: "A grandmaster's brain shows different activity patterns than a novice's — they use long-term memory, not just calculation.", category: "science" },
  { id: 297, type: "fact", text: "The term 'blitz' comes from the German word for 'lightning' — typically 3 or 5 minute games.", category: "trivia" },
  { id: 298, type: "fact", text: "Anatoly Karpov is estimated to have played over 30,000 competitive games in his career.", category: "records" },
  { id: 299, type: "fact", text: "The first computer to achieve grandmaster-level play was Deep Thought (1988), a precursor to Deep Blue.", category: "technology" },
  { id: 300, type: "fact", text: "Chess problems (composed puzzles) have their own rating system and competitions, separate from over-the-board play.", category: "trivia" },
  { id: 301, type: "fact", text: "Kramnik's 'toilet break controversy' with Topalov (2006) led to the term 'Toiletgate' in chess.", category: "trivia" },
  { id: 302, type: "fact", text: "Bobby Fischer invented his own chess variant (Chess960/Fischer Random) to combat opening memorization.", category: "history" },
  { id: 303, type: "fact", text: "Lichess, the popular chess platform, is open-source and completely free, funded by donations.", category: "technology" },
  { id: 304, type: "fact", text: "The Candidates Tournament determines the challenger for the World Championship title.", category: "trivia" },
  { id: 305, type: "fact", text: "Alexander Alekhine is the only world champion to die while still holding the title (1946).", category: "history" },
  { id: 306, type: "fact", text: "In tournament chess, touching a piece means you must move it (the 'touch-move' rule).", category: "trivia" },
  { id: 307, type: "fact", text: "There are more possible chess games than grains of sand on all the beaches on Earth.", category: "math" },
  { id: 308, type: "fact", text: "The Najdorf Sicilian is named after Miguel Najdorf, who played it to draw attention and help find his family after WWII.", category: "history" },
  { id: 309, type: "fact", text: "Chess engines evaluate positions in centipawns (1/100th of a pawn), allowing precise positional comparisons.", category: "technology" },
  { id: 310, type: "fact", text: "The Evans Gambit (1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 4.b4) was played on a ship by Captain William Evans in 1827.", category: "history" },

  // ──────────────────────────────────────────────────────────────────
  //  PATTERNS (311–400)
  // ──────────────────────────────────────────────────────────────────
  { id: 311, type: "pattern", text: "Back-rank mate: when the king is trapped on the first rank by its own pawns, a rook or queen delivers checkmate.", category: "tactics" },
  { id: 312, type: "pattern", text: "Smothered mate: a knight checkmates a king surrounded by its own pieces. Nf7, Qg8+, Nf7+ is the classic sequence.", category: "tactics" },
  { id: 313, type: "pattern", text: "Greek Gift sacrifice: Bxh7+ Kxh7, Ng5+ Kg8, Qh5 — a devastating attack against a castled king.", category: "tactics" },
  { id: 314, type: "pattern", text: "Anastasia's mate: a rook on the h-file and knight on e7 (or similar) mate the king trapped by its own pawn on g7.", category: "tactics" },
  { id: 315, type: "pattern", text: "Arabian mate: a rook and knight coordinate to trap and mate the king in the corner.", category: "tactics" },
  { id: 316, type: "pattern", text: "Epaulette mate: the king is mated by a queen when two of its own pieces block its escape on adjacent squares.", category: "tactics" },
  { id: 317, type: "pattern", text: "Double bishop sacrifice (Lasker-Bauer sacrifice): Bxh7+ followed by Bxg7 to destroy the castled king's shelter.", category: "tactics" },
  { id: 318, type: "pattern", text: "Clearance sacrifice: move a piece out of the way (even by sacrificing it) to open a line for another piece.", category: "tactics" },
  { id: 319, type: "pattern", text: "Battery: two pieces lined up on the same file, rank, or diagonal (e.g., Q+B on the same diagonal).", category: "tactics" },
  { id: 320, type: "pattern", text: "Outpost: a square in enemy territory protected by a pawn where your piece (usually a knight) can't be driven away.", category: "positional" },
  { id: 321, type: "pattern", text: "Pawn chain: a diagonal line of pawns (e.g., d4-e5-f6). Attack the base of the chain to break it.", category: "positional" },
  { id: 322, type: "pattern", text: "Pawn storm: advancing your pawns towards the opponent's king to open lines for attack.", category: "tactics" },
  { id: 323, type: "pattern", text: "Minority attack: advance 2 pawns against 3 on the queenside (b4-b5) to create weaknesses.", category: "positional" },
  { id: 324, type: "pattern", text: "Blockade: place a piece (ideally a knight) on the square in front of an isolated or passed pawn to restrain it.", category: "positional" },
  { id: 325, type: "pattern", text: "Pawn break: a timely pawn advance (like …d5 or …f5 or c5) to challenge the opponent's center.", category: "positional" },
  { id: 326, type: "pattern", text: "Fianchetto: developing a bishop to g2/b2/g7/b7, controlling the long diagonal.", category: "positional" },
  { id: 327, type: "pattern", text: "Hook mate: a rook-pawn (h-pawn) blocks the king's escape, while a rook on the open file delivers mate.", category: "tactics" },
  { id: 328, type: "pattern", text: "Boden's mate: two bishops crisscross to checkmate a king on c8/c1, often after a queen sacrifice.", category: "tactics" },
  { id: 329, type: "pattern", text: "Philidor's legacy: a smothered mate involving queen sacrifice on g8, discovered check, then Nf7#.", category: "tactics" },
  { id: 330, type: "pattern", text: "Rook lift: moving a rook from the back rank to the third or fourth rank, then swinging it laterally to attack.", category: "tactics" },
  { id: 331, type: "pattern", text: "Zugzwang: a position where any move worsens the player's position. Common in endgames.", category: "endgame" },
  { id: 332, type: "pattern", text: "Fortress: a defensive formation (often with a bishop or rook) that holds a draw despite material disadvantage.", category: "endgame" },
  { id: 333, type: "pattern", text: "Stalemate trick: when losing, aim for stalemate by sacrificing all remaining pieces.", category: "endgame" },
  { id: 334, type: "pattern", text: "Opposition: in K+P endgames, the player whose turn it is to move when kings face each other is at a disadvantage.", category: "endgame" },
  { id: 335, type: "pattern", text: "Triangulation: a king moves in a triangle to reach the same position with the opponent to move.", category: "endgame" },
  { id: 336, type: "pattern", text: "Distant opposition: when kings are separated by an odd number of squares on a rank, file, or diagonal.", category: "endgame" },
  { id: 337, type: "pattern", text: "Corresponding squares: in complex pawn endgames, squares that correspond between the two kings determine the outcome.", category: "endgame" },
  { id: 338, type: "pattern", text: "Breakthrough: a sudden pawn sacrifice to create a passed pawn (e.g., three pawns vs three — push the center pawn).", category: "endgame" },
  { id: 339, type: "pattern", text: "Wrong-colored bishop: with a rook pawn (a or h pawn) and bishop of the wrong color, the endgame is drawn.", category: "endgame" },
  { id: 340, type: "pattern", text: "Réti maneuver: the king moves diagonally to support its own pawn AND stop the opponent's pawn simultaneously.", category: "endgame" },
  { id: 341, type: "pattern", text: "The IQP (Isolated Queen Pawn): gives piece activity and attacking chances but becomes a weakness in endgames.", category: "positional" },
  { id: 342, type: "pattern", text: "Maróczy Bind: pawns on c4 and e4 restrict Black's pieces, especially in Sicilian structures.", category: "positional" },
  { id: 343, type: "pattern", text: "Hedgehog: a flexible structure where Black's pawns sit on the 6th rank (a6, b6, d6, e6) and counter when cramped.", category: "positional" },
  { id: 344, type: "pattern", text: "Carlsbad structure: after cxd5 exd5 in QGD-type positions, creating a minority attack opportunity.", category: "positional" },
  { id: 345, type: "pattern", text: "Stonewall: pawns on c3, d4, e3, f4 (for White) create a wall but leave the e4 square weak.", category: "positional" },
  { id: 346, type: "pattern", text: "King's Indian pawn structure (e5 vs d6): Black attacks on the kingside, White expands on the queenside.", category: "positional" },
  { id: 347, type: "pattern", text: "Exchange sacrifice: giving up a rook for a minor piece to gain positional advantages (common in the Sicilian).", category: "positional" },
  { id: 348, type: "pattern", text: "Undermining: attacking the pawn that supports a key pawn or piece to collapse the structure.", category: "positional" },
  { id: 349, type: "pattern", text: "Overprotection (Nimzowitsch): defending key squares with more pieces than necessary to create flexibility.", category: "positional" },
  { id: 350, type: "pattern", text: "Good vs bad knight: a knight in a closed position with outposts can dominate a bishop hemmed in by its own pawns.", category: "positional" },
  { id: 351, type: "pattern", text: "Bxh6 sacrifice: destroying the kingside pawn cover in Sicilian/French positions where the king castled short.", category: "tactics" },
  { id: 352, type: "pattern", text: "Queen sacrifice for perpetual: when losing, sacrifice the queen for a forced repetition of checks.", category: "tactics" },
  { id: 353, type: "pattern", text: "Discovered attack: moving one piece reveals an attack from another piece behind it.", category: "tactics" },
  { id: 354, type: "pattern", text: "Attraction sacrifice: sacrifice a piece to lure the enemy king or piece to a vulnerable square.", category: "tactics" },
  { id: 355, type: "pattern", text: "Removing the defender: capture or deflect a piece that guards something important.", category: "tactics" },
  { id: 356, type: "pattern", text: "Trapped piece: a piece with no safe squares to retreat to. Common with bishops on a6/h3 and knights on the rim.", category: "tactics" },
  { id: 357, type: "pattern", text: "Pawn fork: a pawn attacking two pieces simultaneously. Often decisive in the endgame.", category: "tactics" },
  { id: 358, type: "pattern", text: "Double check: both a discovered attacker and the moving piece give check. The king must move.", category: "tactics" },
  { id: 359, type: "pattern", text: "Skewer: attacking a valuable piece that, when it moves, exposes a less valuable piece behind it.", category: "tactics" },
  { id: 360, type: "pattern", text: "Pin: attacking a piece that can't move because a more valuable piece behind it would be exposed.", category: "tactics" },
  { id: 361, type: "pattern", text: "Absolute pin: a pin against the king. The pinned piece literally cannot move (it's illegal).", category: "tactics" },
  { id: 362, type: "pattern", text: "Relative pin: a pin against a valuable piece (like the queen). The pinned piece CAN move but it's usually bad.", category: "tactics" },
  { id: 363, type: "pattern", text: "Windmill: alternating discovered checks (usually with a rook and bishop) to win massive material.", category: "tactics" },
  { id: 364, type: "pattern", text: "Perpetual check: a series of checks that cannot be escaped, forcing a draw. The defender's saving resource.", category: "tactics" },
  { id: 365, type: "pattern", text: "X-ray attack: a piece attacks through another piece. E.g., a rook on a1 defends a1 even with a piece on a4.", category: "tactics" },
  { id: 366, type: "pattern", text: "Intermezzo (in-between move): instead of making the expected recapture, play an intermediate forcing move first.", category: "tactics" },

  // Extra tips to go beyond 366
  { id: 367, type: "tip", text: "After castling, keep at least one rook connected to the castled king for defensive purposes.", category: "middlegame" },
  { id: 368, type: "tip", text: "In rapid games, use your opponent's time to calculate your next moves. Don't just wait.", category: "general" },
  { id: 369, type: "tip", text: "Develop your knights before your bishops — knights have fewer good squares and need more moves to get active.", category: "opening" },
  { id: 370, type: "quote", text: "The blunders are all there on the board, waiting to be made.", author: "Savielly Tartakower" },
  { id: 371, type: "tip", text: "When both sides have traded queens, the endgame is often decided by pawn structure and king activity.", category: "endgame" },
  { id: 372, type: "fact", text: "The shortest recorded decisive tournament game lasted just one move — a player forfeited by not showing up.", category: "trivia" },
  { id: 373, type: "pattern", text: "Lucena position: the most important rook endgame win. Build a bridge with your rook to shelter the king from checks.", category: "endgame" },
  { id: 374, type: "pattern", text: "Philidor position: the key drawing technique in R+P vs R. Keep your rook on the 6th rank until the pawn advances.", category: "endgame" },
  { id: 375, type: "tip", text: "Record your thought process during key moves. Reviewing your reasoning is more valuable than reviewing the moves themselves.", category: "improvement" },
  { id: 376, type: "quote", text: "In chess, you don't always learn from winning. Losing is the greatest teacher.", author: "José Raúl Capablanca" },
  { id: 377, type: "tip", text: "When your opponent has a cramped position, don't rush. Improve your pieces slowly — they'll run out of moves.", category: "middlegame" },
  { id: 378, type: "fact", text: "The fastest possible stalemate occurs after just 12 moves (with cooperation from both sides).", category: "trivia" },
  { id: 379, type: "pattern", text: "Dovetail mate: the queen checkmates the king when two of the king's escape squares are blocked by its own pieces.", category: "tactics" },
  { id: 380, type: "tip", text: "Always check if your piece is hanging before making your move. A quick 'blunder check' prevents most losses.", category: "general" },
  { id: 381, type: "quote", text: "Chess is one of the few arts where composition takes place simultaneously with performance.", author: "Garry Kasparov" },
  { id: 382, type: "fact", text: "There are exactly 12 unique pawn structures possible from the starting position after each side pushes one pawn.", category: "math" },
  { id: 383, type: "tip", text: "Don't be afraid to repeat moves when calculating. Repeating can gain time on the clock and force errors.", category: "general" },
  { id: 384, type: "pattern", text: "Pawn majority: when you have more pawns than your opponent on one side, advance them to create a passed pawn.", category: "endgame" },
  { id: 385, type: "tip", text: "Sleep well before a tournament game. Cognitive performance drops significantly with poor sleep.", category: "general" },
  { id: 386, type: "quote", text: "To improve at chess you should in the first instance study the endgame.", author: "José Raúl Capablanca" },
  { id: 387, type: "tip", text: "Use the principle of elimination: if only one move doesn't lose, it must be the right move.", category: "tactics" },
  { id: 388, type: "fact", text: "The Chess Olympiad has been held since 1927 and is the largest team chess event in the world.", category: "history" },
  { id: 389, type: "pattern", text: "Damiano's mate: a queen sacrifice followed by a back-rank mate with a rook. Classic queen+rook teamwork.", category: "tactics" },
  { id: 390, type: "tip", text: "Coordinate your pieces toward one goal. Don't have pieces attacking on opposite sides — concentrate force.", category: "middlegame" },
  { id: 391, type: "quote", text: "Chess is the art of analysis.", author: "Mikhail Botvinnik" },
  { id: 392, type: "fact", text: "The first email chess game was played in 1970 between the US Army and the Soviet Academy of Sciences.", category: "history" },
  { id: 393, type: "tip", text: "Learn to use your a and h pawns in the endgame. They create threats on the wings even when behind in development.", category: "endgame" },
  { id: 394, type: "pattern", text: "Rook on the 7th: a rook on the opponent's second rank attacks pawns from behind and restricts the king.", category: "positional" },
  { id: 395, type: "quote", text: "I believe that chess is a matter of intuition, but you can't separate intuition from knowledge.", author: "Viswanathan Anand" },
  { id: 396, type: "tip", text: "When you're worse, complicate. When you're better, simplify. Match your play to the position's demands.", category: "general" },
  { id: 397, type: "fact", text: "Garry Kasparov's loss to Deep Blue in 1997 is often cited as a turning point in the relationship between humans and computers.", category: "history" },
  { id: 398, type: "pattern", text: "Pawn chain tension: maintaining tension (not resolving captures) gives you options. Release at the right moment.", category: "positional" },
  { id: 399, type: "tip", text: "Endgame study tip: learn the Vancura position in R+P vs R — the drawing setup with a rook on the a-file.", category: "endgame" },
  { id: 400, type: "quote", text: "If you wish to succeed, you must brave the risk of failure.", author: "Garry Kasparov" },
];

/**
 * Get today's daily tip, rotating by day of year.
 */
export function getTodayTip(): DailyTip {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return DAILY_TIPS[dayOfYear % DAILY_TIPS.length];
}

/**
 * Get a specific tip by index (for cycling through).
 */
export function getTipByIndex(index: number): DailyTip {
  return DAILY_TIPS[((index % DAILY_TIPS.length) + DAILY_TIPS.length) % DAILY_TIPS.length];
}

export const TIP_TYPE_LABELS: Record<string, { icon: string; label: string; color: string }> = {
  quote: { icon: "💬", label: "Quote", color: "text-blue-400" },
  tip: { icon: "💡", label: "Tip", color: "text-emerald-400" },
  fact: { icon: "📚", label: "Fact", color: "text-amber-400" },
  pattern: { icon: "🧩", label: "Pattern", color: "text-fuchsia-400" },
};
