import React from 'react';
import {AbsoluteFill, Audio, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame} from 'remotion';

const C={bg:'#111629',ink:'#fff1d0',lime:'#d7fa64',purple:'#ad95ff',blue:'#698fba'};
const asset=(name:string)=>staticFile(`chaos-promo/${name}`);
const clamp={extrapolateLeft:'clamp',extrapolateRight:'clamp'} as const;
const pop=(f:number,delay=0)=>spring({frame:f-delay,fps:30,config:{damping:13,stiffness:190,mass:.7}});
function Tag({children,color=C.lime}:{children:React.ReactNode;color?:string}){return <div style={{fontFamily:'Arial',fontWeight:800,fontSize:23,letterSpacing:4,color,textTransform:'uppercase'}}>{children}</div>}
function Head({children,size=110,color=C.ink,delay=0}:{children:React.ReactNode;size?:number;color?:string;delay?:number}){const f=useCurrentFrame();return <div style={{fontFamily:'Impact',fontSize:size,lineHeight:1.02,letterSpacing:1,color,textTransform:'uppercase',transform:`translateY(${(1-pop(f,delay))*55}px) scale(${.92+.08*pop(f,delay)})`,opacity:interpolate(f,[delay,delay+5],[0,1],clamp),textShadow:'0 6px 0 #060b19'}}>{children}</div>}
function Burst({at=0,color=C.lime}:{at?:number;color?:string}){const f=useCurrentFrame()-at;return <AbsoluteFill style={{pointerEvents:'none'}}>{Array.from({length:18},(_,i)=>{const a=i*Math.PI*2/18,r=interpolate(f,[0,23],[20,620],clamp);return <div key={i} style={{position:'absolute',left:540+Math.cos(a)*r,top:870+Math.sin(a)*r,width:7,height:45,background:color,transform:`rotate(${a*180/Math.PI+90}deg)`,opacity:f<0?0:interpolate(f,[0,20],[1,0],clamp)}}/>})}</AbsoluteFill>}
function Frame({children}:{children:React.ReactNode}){const f=useCurrentFrame();return <AbsoluteFill style={{background:C.bg,color:C.ink,overflow:'hidden',fontFamily:'Arial'}}><AbsoluteFill style={{background:'radial-gradient(ellipse at 50% 52%,#40567077,transparent 68%)'}}/><div style={{position:'absolute',inset:-300,opacity:.07,backgroundImage:'linear-gradient(45deg,#d7fa64 25%,transparent 25%,transparent 75%,#d7fa64 75%),linear-gradient(45deg,#d7fa64 25%,transparent 25%,transparent 75%,#d7fa64 75%)',backgroundSize:'160px 160px',backgroundPosition:`${f*.15}px ${f*.2}px,${80+f*.15}px ${80+f*.2}px`,transform:'rotate(-12deg)'}}/><div style={{position:'absolute',top:200,left:75,display:'flex',alignItems:'center',gap:16}}><Img src={asset('logo.svg')} style={{width:47,height:47}}/><Tag>CHAOS CHESS</Tag></div>{children}<div style={{position:'absolute',left:75,right:75,bottom:265,height:5,background:'#ffffff15'}}><div style={{height:5,width:`${f/719*100}%`,background:C.lime}}/></div></AbsoluteFill>}
function Hook(){const f=useCurrentFrame();const typed='en passant'.slice(0,Math.floor(Math.max(0,f-12)/2));return <><div style={{position:'absolute',left:75,right:75,top:335}}><Head size={118}>WE GOOGLED<br/><span style={{color:C.lime}}>EN PASSANT.</span></Head><div style={{marginTop:48,padding:'30px 35px',border:'3px solid #8995b5',borderRadius:25,background:'#222b41',fontSize:42,fontFamily:'Arial',display:'flex',gap:24}}><span style={{color:C.purple}}>⌕</span>{typed}<span style={{color:C.lime}}>|</span></div></div><Img src={asset('wP.svg')} style={{position:'absolute',width:390,height:390,left:345,top:900,transform:`translateY(${Math.sin(f*.09)*15}px) rotate(${Math.sin(f*.05)*5}deg)`,filter:'drop-shadow(0 30px 25px #0008)'}}/><div style={{position:'absolute',top:1390,width:'100%',textAlign:'center'}}><Tag color={C.purple}>a perfectly normal chess game.</Tag></div></>}
function Hell(){const f=useCurrentFrame();return <><Burst at={2}/><div style={{position:'absolute',inset:0,background:C.lime,opacity:interpolate(f,[0,3,9],[.7,.25,0],clamp)}}/><div style={{position:'absolute',top:430,left:60,right:60,textAlign:'center',transform:`rotate(${Math.sin(f*2)*Math.max(0,8-f/3)}deg)`}}><Head size={182}>HOLY<br/><span style={{color:C.lime}}>HELL.</span></Head><div style={{marginTop:60}}><Head size={72} delay={14}>IT GOT OUT<br/>OF HAND.</Head></div></div><div style={{position:'absolute',left:100,right:100,top:1240,background:'#ad95ff',color:C.bg,borderRadius:18,padding:28,textAlign:'center',fontSize:31,fontWeight:900,transform:'rotate(-4deg)'}}>NORMAL CHESS LEFT THE CHAT</div></>}
function Card({name,img,x,angle,index,selected,atlas=false}:{name:string;img:string;x:number;angle:number;index:number;selected:boolean;atlas?:boolean}){const f=useCurrentFrame();const p=pop(f,index*5);const picked=selected&&f>44;return <div style={{position:'absolute',left:x,top:690+(1-p)*450-(picked?35:0),width:282,borderRadius:26,overflow:'hidden',background:'#24334b',border:`${picked?7:3}px solid ${picked?C.lime:'#788ca4'}`,boxShadow:picked?'0 0 65px #d7fa6455,0 15px 0 #070d1a':'0 14px 0 #070d1a',transform:`rotate(${picked?0:angle}deg) scale(${picked?1.12:1})`}}>{atlas?<div style={{height:330,backgroundImage:`url(${asset(img)})`,backgroundSize:'200% 200%',backgroundPosition:'0% 0%'}}/>:<Img src={asset(img)} style={{width:'100%',height:330,objectFit:'cover'}}/>}<div style={{padding:21,height:125}}><div style={{fontSize:16,color:C.purple,letterSpacing:2,fontWeight:900}}>{selected?'RARE':'COMMON'}</div><div style={{fontFamily:'Impact',fontSize:34,marginTop:12}}>{name}</div></div>{picked&&<div style={{position:'absolute',top:12,right:12,background:C.lime,color:C.bg,width:48,height:48,borderRadius:24,display:'grid',placeItems:'center',fontSize:32,fontWeight:900}}>✓</div>}</div>}
function Draft(){const f=useCurrentFrame();return <><div style={{position:'absolute',top:340,left:75,right:75}}><Tag color={C.purple}>NEW RESPONSE JUST DROPPED</Tag><div style={{marginTop:25}}><Head size={115}>DRAFT YOUR<br/><span style={{color:C.lime}}>BAD IDEA.</span></Head></div></div><Card name="TORPEDO PAWNS" img="toy-sheet.webp" atlas x={65} angle={-7} index={0} selected={false}/><Card name="THE KNOOK" img="knook.webp" x={400} angle={2} index={1} selected/><Card name="DRAGON ROOK" img="dragon-rook.webp" x={735} angle={8} index={2} selected={false}/><div style={{position:'absolute',left:75,right:75,top:1320,textAlign:'center'}}><Head size={56} delay={48}>{f>44?'KNIGHT + ROOK. YES, REALLY.':'THREE POWERS. ONE PICK.'}</Head></div></>}
function Knook(){const f=useCurrentFrame();const change=f>22;return <><Burst at={23} color={C.purple}/><div style={{position:'absolute',top:340,left:75,right:75}}><Head size={118}>THE <span style={{color:C.lime}}>KNOOK</span><br/>IS REAL.</Head></div><div style={{position:'absolute',top:700,left:215,width:650,height:650,borderRadius:70,background:'radial-gradient(circle,#69775d55,transparent 70%)',transform:`scale(${.9+.1*pop(f,22)}) rotate(${Math.sin(f*.08)*3}deg)`}}><Img src={asset(change?'wC.svg':'wN.svg')} style={{width:'100%',height:'100%',filter:'drop-shadow(0 25px 25px #0009)'}}/></div><div style={{position:'absolute',top:1390,width:'100%',textAlign:'center'}}><Head size={64} delay={26}>KNIGHT JUMPS.<br/><span style={{color:C.lime}}>ROOK MOVES.</span></Head></div></>}
function Board({attack=false}:{attack?:boolean}){const f=useCurrentFrame();const n=104;const move=interpolate(f,[22,43],[0,1],clamp);const piece=(file:number,rank:number,name:string,opacity=1)=> <Img key={name} src={asset(name+'.svg')} style={{position:'absolute',width:n,height:n,left:file*n,top:rank*n,opacity,filter:'drop-shadow(0 8px 3px #0005)'}}/>;return <div style={{position:'absolute',top:690,left:124,width:832,height:832,border:'12px solid #c8a05d',boxSizing:'content-box',borderRadius:20,boxShadow:'0 16px 0 #775d3b,0 30px 70px #0009',transform:`rotate(${attack?-3:3}deg)`,overflow:'hidden'}}><div style={{display:'grid',gridTemplateColumns:'repeat(8,104px)'}}>{Array.from({length:64},(_,i)=><div key={i} style={{width:n,height:n,background:(Math.floor(i/8)+i%8)%2?'#789da8':'#eee2bd'}}/>)}</div><div style={{position:'absolute',inset:0}}>{piece(0,0,'bK')}{piece(1,7,'wK')}{attack?<><div style={{position:'absolute',left:6*n,top:1*n,width:n,height:5*n,background:'#d7fa6455',opacity:interpolate(f,[10,20],[0,1],clamp)}}/>{piece(6,1,'bQ',1-interpolate(f,[40,46],[0,1],clamp))}{piece(6,5-4*move,'wC')}</>:<><div style={{position:'absolute',left:3*n,top:2*n,width:n,height:3*n,background:'#d7fa6477'}}/>{piece(3,4-2*move,'wP')}{piece(6,1,'bQ')}</>}</div></div>}
function Pawn(){return <><div style={{position:'absolute',top:340,left:75,right:75}}><Tag color={C.purple}>TORPEDO PAWNS</Tag><div style={{marginTop:25}}><Head size={105}>TWO SQUARES.<br/><span style={{color:C.lime}}>ANY RANK.</span></Head></div></div><Board/><div style={{position:'absolute',top:1590,left:100,right:100,textAlign:'center',fontSize:26,color:'#c8d8e7'}}>Your pawns have places to be.</div></>}
function Capture(){const f=useCurrentFrame();return <><div style={{position:'absolute',top:340,left:65,right:65}}><Head size={103}>“THAT’S NOT<br/><span style={{color:C.lime}}>A LEGAL MOVE.”</span></Head><div style={{fontSize:30,color:C.purple,marginTop:22,fontWeight:800}}>— your friend, about to lose a queen</div></div><Board attack/><Burst at={43}/>{f>45&&<div style={{position:'absolute',top:1060,left:120,right:120,transform:'rotate(-9deg)',background:C.lime,color:C.bg,fontFamily:'Impact',fontSize:90,textAlign:'center',padding:16,boxShadow:'0 10px 0 #0008'}}>IT IS NOW.</div>}</>}
function End(){const f=useCurrentFrame();return <><div style={{position:'absolute',top:370,left:75,right:75,textAlign:'center'}}><Img src={asset('logo.svg')} style={{width:170,height:170,transform:`rotate(${Math.sin(f*.1)*4}deg)`}}/><div style={{marginTop:35}}><Head size={155}>CHAOS<br/><span style={{color:C.lime}}>CHESS</span></Head></div><div style={{marginTop:35,fontSize:39,fontWeight:900}}>DRAFT POWERS. BREAK CHESS.</div><div style={{background:'#5865f2',border:'3px solid #b3b6ff',borderRadius:30,padding:'31px 18px',fontSize:49,fontWeight:900,marginTop:75,boxShadow:'0 9px 0 #323b9b',transform:`scale(${1+Math.sin(f*.11)*.015})`}}>PLAY ON DISCORD ↗</div><div style={{fontSize:37,marginTop:26,color:C.lime,fontWeight:800}}>chaos.firechess.com</div><div style={{fontSize:31,marginTop:65,color:'#c7cce3'}}>Send this to your “chess is balanced” friend.</div></div></>}
export const ChaosPromo=()=> <Frame><style>{`@font-face{font-family:Impact;src:url('${asset('impact.ttf')}')}*{box-sizing:border-box}`}</style><Audio src={asset('soundtrack.wav')}/><Sequence from={0} durationInFrames={75}><Hook/></Sequence><Sequence from={75} durationInFrames={75}><Hell/></Sequence><Sequence from={150} durationInFrames={120}><Draft/></Sequence><Sequence from={270} durationInFrames={105}><Knook/></Sequence><Sequence from={375} durationInFrames={90}><Pawn/></Sequence><Sequence from={465} durationInFrames={105}><Capture/></Sequence><Sequence from={570} durationInFrames={150}><End/></Sequence></Frame>;
