import React from "react";
import {
  AbsoluteFill, Audio, Sequence, staticFile,
  interpolate, spring, useCurrentFrame, useVideoConfig,
} from "remotion";
import { loadFont } from "@remotion/google-fonts/SpaceGrotesk";
import { Board } from "./Board";
import analysisData from "./game-analysis.json";

const { fontFamily } = loadFont();

// Real Stockfish analysis of the game (eval per position, per-move classification,
// single-game accuracy) — generated by analyze-game.ts.
const analysis = analysisData as {
  evalWhite: number[];
  moves: { ply: number; san: string; white: boolean; cpLoss: number; classification: string }[];
  whiteAccuracy: number;
  whiteAvgCpLoss: number;
  whiteBlunders: number;
  whiteMistakes: number;
  whiteInaccuracies: number;
};

// Chess.com-style move badges (mirrors lib/move-quality.ts).
const BADGE: Record<string, { e: string; s: string; c: string }> = {
  brilliant: { e: "💎", s: "!!", c: "#06b6d4" },
  best: { e: "✅", s: "!", c: "#10b981" },
  good: { e: "👍", s: "✓", c: "#34d399" },
  book: { e: "📖", s: "book", c: "#94a3b8" },
  inaccuracy: { e: "⚠️", s: "?!", c: "#f59e0b" },
  mistake: { e: "❌", s: "?", c: "#f97316" },
  blunder: { e: "💀", s: "??", c: "#ef4444" },
};
const lerp = (a: number, b: number, t: number) => a + (b - a) * t;
const evalToPct = (cp: number) => 100 / (1 + Math.exp(-cp / 350));

// ---- real game (chess.js-validated): queen never sits on a pawn-takeable square ----
// h5->f3->g3 (all safe), then ...Nd4, White tries c3, ...Ne2+ forks K+Q.
const FENS = [
  "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
  "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
  "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2",
  "rnbqkbnr/pppp1ppp/8/4p3/2B1P3/8/PPPP1PPP/RNBQK1NR b KQkq - 1 2",
  "r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/8/PPPP1PPP/RNBQK1NR w KQkq - 2 3",
  "r1bqkbnr/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 3 3",
  "r1bqkbnr/pppp1p1p/2n3p1/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 0 4",
  "r1bqkbnr/pppp1p1p/2n3p1/4p3/2B1P3/5Q2/PPPP1PPP/RNB1K1NR b KQkq - 1 4",
  "r1bqkb1r/pppp1p1p/2n2np1/4p3/2B1P3/5Q2/PPPP1PPP/RNB1K1NR w KQkq - 2 5",
  "r1bqkb1r/pppp1p1p/2n2np1/4p3/2B1P3/3P1Q2/PPP2PPP/RNB1K1NR b KQkq - 0 5",
  "r1bqk2r/pppp1pbp/2n2np1/4p3/2B1P3/3P1Q2/PPP2PPP/RNB1K1NR w KQkq - 1 6",
  "r1bqk2r/pppp1pbp/2n2np1/4p3/2B1P3/3P1Q1N/PPP2PPP/RNB1K2R b KQkq - 2 6",
  "r1bq1rk1/pppp1pbp/2n2np1/4p3/2B1P3/3P1Q1N/PPP2PPP/RNB1K2R w KQ - 3 7",
  "r1bq1rk1/pppp1pbp/2n2np1/4p3/2B1P3/3P1Q1N/PPP2PPP/RNB2RK1 b - - 4 7",
  "r1bq1rk1/ppp2pbp/2np1np1/4p3/2B1P3/3P1Q1N/PPP2PPP/RNB2RK1 w - - 0 8",
  "r1bq1rk1/ppp2pbp/2np1np1/4p3/2B1P3/3P2QN/PPP2PPP/RNB2RK1 b - - 1 8", // 15: Qg3
  "r1bq1rk1/ppp2pbp/3p1np1/4p3/2BnP3/3P2QN/PPP2PPP/RNB2RK1 w - - 2 9", // 16: ...Nd4
  "r1bq1rk1/ppp2pbp/3p1np1/4p3/2BnP3/2PP2QN/PP3PPP/RNB2RK1 b - - 0 9", // 17: c3 (kick)
  "r1bq1rk1/ppp2pbp/3p1np1/4p3/2B1P3/2PP2QN/PP2nPPP/RNB2RK1 w - - 1 10", // 18: ...Ne2+ FORK
  "r1bq1rk1/ppp2pbp/3p1np1/4p3/2B1P3/2PP2QN/PP2nPPP/RNB2R1K b - - 2 10", // 19: Kh1
  "r1bq1rk1/ppp2pbp/3p1np1/4p3/2B1P3/2PP2nN/PP3PPP/RNB2R1K w - - 0 11", // 20: ...Nxg3 queen gone
];
const SANS = ["e4","e5","Bc4","Nc6","Qh5","g6","Qf3","Nf6","d3","Bg7","Nh3","O-O","O-O","d6","Qg3","Nd4","c3","Ne2+","Kh1","Nxg3"];
const MOVES: { to: string; q: boolean }[] = [
  {to:"e4",q:false},{to:"e5",q:false},{to:"c4",q:false},{to:"c6",q:false},{to:"h5",q:true},{to:"g6",q:false},{to:"f3",q:true},{to:"f6",q:false},{to:"d3",q:false},{to:"g7",q:false},{to:"h3",q:false},{to:"g8",q:false},{to:"g1",q:false},{to:"d6",q:false},{to:"g3",q:true},
];

const BOARD = 760;
const C = { amber: "#fbbf24", purple: "#a855f7", purpleLt: "#c084fc", red: "#f87171", dim: "#94a3b8", green: "#6ee7b7", yellow: "rgba(250,204,21,0.95)" };
const clamp = { extrapolateLeft: "clamp" as const, extrapolateRight: "clamp" as const };

// Real eval bar: white fill height from a centipawn value (White's perspective).
const EvalBar: React.FC<{ cp: number }> = ({ cp }) => (
  <div style={{ position: "absolute", left: -34, top: 0, width: 18, height: "100%", background: "#15131c", borderRadius: 9, overflow: "hidden", display: "flex", flexDirection: "column-reverse" }}>
    <div style={{ width: "100%", height: `${evalToPct(cp)}%`, background: "#f0f0f0" }} />
  </div>
);

const MoveBadge: React.FC<{ cls: string }> = ({ cls }) => {
  const b = BADGE[cls];
  if (!b) return null;
  return (
    <span style={{ display: "inline-flex", alignItems: "center", gap: 8, fontSize: 36, fontWeight: 900, color: b.c, background: `${b.c}22`, border: `2px solid ${b.c}66`, borderRadius: 12, padding: "6px 16px" }}>
      {b.e} {b.s}
    </span>
  );
};

const FadeScene: React.FC<{ dur: number; children: React.ReactNode }> = ({ dur, children }) => {
  const f = useCurrentFrame();
  const opacity = interpolate(f, [0, 8, dur - 8, dur], [0, 1, 1, 0], clamp);
  return <AbsoluteFill style={{ opacity, alignItems: "center", justifyContent: "center", padding: "140px 70px", textAlign: "center" }}>{children}</AbsoluteFill>;
};

const usePop = (delay = 0) => {
  const f = useCurrentFrame();
  const { fps } = useVideoConfig();
  const s = spring({ frame: f - delay, fps, config: { damping: 13, stiffness: 130 } });
  return { opacity: interpolate(f, [delay, delay + 7], [0, 1], clamp), transform: `translateY(${interpolate(s, [0, 1], [40, 0])}px) scale(${interpolate(s, [0, 1], [0.85, 1])})` };
};
const Hooked: React.FC<{ children: React.ReactNode; size?: number; delay?: number }> = ({ children, size = 90, delay = 0 }) => {
  const st = usePop(delay);
  return <div style={{ ...st, fontSize: size, fontWeight: 900, lineHeight: 1.07, letterSpacing: -1, textShadow: "0 6px 30px rgba(0,0,0,.5)" }}>{children}</div>;
};
const FadeUp: React.FC<{ delay?: number; style?: React.CSSProperties; children: React.ReactNode }> = ({ delay = 0, style, children }) => {
  const f = useCurrentFrame();
  return <div style={{ ...style, opacity: interpolate(f, [delay, delay + 10], [0, 1], clamp), transform: `translateY(${interpolate(f, [delay, delay + 10], [20, 0], clamp)}px)` }}>{children}</div>;
};
const CapTop: React.FC<{ children: React.ReactNode; color?: string }> = ({ children, color }) => (
  <FadeUp style={{ position: "absolute", top: 130, left: 0, right: 0, padding: "0 80px", fontSize: 56, fontWeight: 800, lineHeight: 1.16, color }}>{children}</FadeUp>
);
const hl: React.CSSProperties = { color: C.amber, textShadow: "0 0 40px rgba(251,191,36,.5)" };

const Emoji: React.FC<{ ch: string; i?: number; size?: number }> = ({ ch, i = 0, size = 96 }) => {
  const f = useCurrentFrame();
  const s = 1 + 0.13 * Math.sin((f + i * 9) * 0.35);
  const r = Math.sin((f + i * 11) * 0.28) * 9;
  return <span style={{ display: "inline-block", fontSize: size, transform: `scale(${s}) rotate(${r}deg)` }}>{ch}</span>;
};

// ---------------- HOOK ----------------
const S_Hook: React.FC = () => {
  const f = useCurrentFrame();
  const shakeAmp = interpolate(f, [0, 55], [12, 0], clamp);
  const shake = `translate(${Math.sin(f * 1.9) * shakeAmp}px, ${Math.cos(f * 2.7) * shakeAmp * 0.55}px)`;
  const A = interpolate(f, [0, 5, 46, 56], [0, 1, 1, 0], clamp);
  const B = interpolate(f, [50, 60, 102, 114], [0, 1, 1, 0], clamp);
  const Bscale = interpolate(spring({ frame: f - 50, fps: 30, config: { damping: 12, stiffness: 160 } }), [0, 1], [0.6, 1]);
  const D = interpolate(f, [110, 124], [0, 1], clamp);
  return (
    <AbsoluteFill style={{ transform: shake }}>
      <AbsoluteFill style={{ alignItems: "center", justifyContent: "center", opacity: A, flexDirection: "column", gap: 20 }}>
        <span style={{ fontSize: 150 }}>💀</span>
        <div style={{ fontSize: 150, fontWeight: 900, color: C.amber, textShadow: "0 0 50px rgba(251,191,36,.5)" }}>700 ELO<span style={{ color: C.red }}>?!</span></div>
      </AbsoluteFill>
      <AbsoluteFill style={{ alignItems: "center", justifyContent: "center", opacity: B, flexDirection: "column", gap: 28 }}>
        <div style={{ transform: `scale(${Bscale})` }}><Board id="hookflash" fen={FENS[18]} size={520} rings={{ g1: C.red, g3: C.red, e2: C.amber }} /></div>
        <div style={{ fontSize: 64, fontWeight: 900, color: "#fff" }}>wait for it… 👀</div>
      </AbsoluteFill>
      <AbsoluteFill style={{ alignItems: "center", justifyContent: "center", opacity: D, flexDirection: "column", gap: 30, padding: "0 60px" }}>
        <div style={{ display: "flex", gap: 20 }}><Emoji ch="💀" i={0} /><Emoji ch="🤡" i={1} /><Emoji ch="😬" i={2} /></div>
        <Hooked delay={112} size={96}>An AI just<br /><span style={hl}>roasted</span> his chess</Hooked>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};

// ---------------- GAME PLAYBACK (moves 1–15) ----------------
const S_Game: React.FC = () => {
  const f = useCurrentFrame();
  const INTRO = 10, PERPLY = 17;
  const cont = f < INTRO ? 0 : (f - INTRO) / PERPLY;
  const ply = f < INTRO ? 0 : Math.min(15, Math.floor(cont) + 1);
  const mv = ply >= 1 ? MOVES[ply - 1] : null;
  const rings: Record<string, string> = mv ? { [mv.to]: mv.q ? C.amber : C.yellow } : {};
  const moveNo = Math.ceil(ply / 2);
  const label = ply >= 1 ? `${moveNo}.${ply % 2 ? "" : ".."} ${SANS[ply - 1]}` : "";
  // real eval bar: ease toward the current ply's eval after the move lands
  const fracInto = ply === 0 ? 0 : Math.min(1, Math.max(0, (cont - (ply - 1)) / 0.55));
  const cp = ply === 0 ? analysis.evalWhite[0] : lerp(analysis.evalWhite[ply - 1], analysis.evalWhite[ply], fracInto);
  const cls = ply >= 1 ? analysis.moves[ply - 1].classification : null;
  return (
    <>
      <CapTop>Scholar's mate… that <span style={hl}>fails</span>.</CapTop>
      <div style={{ position: "relative", width: BOARD, height: BOARD }}>
        <EvalBar cp={cp} />
        <Board id="game" fen={FENS[ply]} size={BOARD} rings={rings} />
      </div>
      <div style={{ position: "absolute", bottom: 130, left: 0, right: 0, display: "flex", alignItems: "center", justifyContent: "center", gap: 18, minHeight: 64 }}>
        <span style={{ fontSize: 54, fontWeight: 800, fontFamily: "ui-monospace, monospace", color: mv?.q ? C.amber : "#fff" }}>{label}</span>
        {cls && fracInto > 0.4 ? <MoveBadge cls={cls} /> : null}
      </div>
    </>
  );
};

// ---------------- THE FORK ----------------
const S_Fork: React.FC = () => {
  const f = useCurrentFrame();
  let idx = 16, rings: Record<string, string> = { d4: C.yellow }, label = "16… Nd4", labelColor = "#fff", cap = "A knight lands on d4…", capColor: string | undefined;
  if (f >= 200) { idx = 20; rings = { g3: C.red }; label = "Nxg3 — queen gone 💀"; labelColor = C.red; cap = "Game over."; capColor = C.red; }
  else if (f >= 108) { idx = 18; rings = { g1: C.red, g3: C.red, e2: C.amber }; label = "Ne2+  ♞  FORK!"; labelColor = C.amber; cap = "King AND queen. 🍴"; capColor = C.red; }
  else if (f >= 45) { idx = 17; rings = { d4: C.red }; label = "c3 — kick it!"; labelColor = "#fff"; cap = "He tries to kick it…"; }
  const flash = f < 200 ? 0 : interpolate(f, [200, 226], [0.85, 0], clamp);
  const forkPulse = f >= 108 && f < 200 ? 1 + 0.04 * Math.sin(f * 0.6) : 1;
  return (
    <>
      <CapTop color={capColor}>{cap}</CapTop>
      <div style={{ position: "relative", width: BOARD, height: BOARD, transform: `scale(${forkPulse})` }}>
        <EvalBar cp={analysis.evalWhite[idx]} />
        <Board id="fork" fen={FENS[idx]} size={BOARD} rings={rings} />
        <div style={{ position: "absolute", inset: 0, borderRadius: 14, background: "radial-gradient(circle, rgba(248,113,113,.55), transparent 68%)", opacity: flash }} />
      </div>
      <div style={{ position: "absolute", bottom: 130, left: 0, right: 0, display: "flex", alignItems: "center", justifyContent: "center", gap: 18 }}>
        <span style={{ fontSize: 60, fontWeight: 900, fontFamily: "ui-monospace, monospace", color: labelColor }}>{label}</span>
        {idx === 17 ? <MoveBadge cls="blunder" /> : null}
      </div>
    </>
  );
};

// ---------------- ROAST CARD ----------------
const RoastLine: React.FC<{ delay: number; style?: React.CSSProperties; children: React.ReactNode }> = ({ delay, style, children }) => {
  const f = useCurrentFrame();
  return <div style={{ fontSize: 46, fontWeight: 700, lineHeight: 1.3, margin: "18px 0", opacity: interpolate(f, [delay, delay + 8], [0, 1], clamp), transform: `translateX(${interpolate(f, [delay, delay + 8], [-16, 0], clamp)}px)`, ...style }}>{children}</div>;
};
const S_Roast: React.FC = () => (
  <div style={{ width: 880, background: "linear-gradient(160deg,#1c1030,#120a22)", border: "2px solid rgba(168,85,247,.4)", borderRadius: 28, padding: "50px 44px", boxShadow: "0 20px 80px rgba(120,40,200,.3)", textAlign: "left" }}>
    <div style={{ fontSize: 32, fontWeight: 900, letterSpacing: 2, color: C.red, marginBottom: 28 }}>☠ CAUSE OF DEATH</div>
    <RoastLine delay={10}>A knight fork on move 9.</RoastLine>
    <RoastLine delay={55}>Queen tour: h5 → f3 → g3.</RoastLine>
    <RoastLine delay={100}>Out on move 3. <span style={{ color: C.red }}>Babysat till it died.</span></RoastLine>
    <RoastLine delay={150} style={{ color: C.purpleLt, fontWeight: 800, marginTop: 32 }}>He never saw it coming.</RoastLine>
  </div>
);

const Stat: React.FC<{ value: string; label: string; color: string; delay: number }> = ({ value, label, color, delay }) => {
  const st = usePop(delay);
  return (
    <div style={{ flex: 1, background: "rgba(255,255,255,.04)", border: "2px solid rgba(255,255,255,.1)", borderRadius: 22, padding: "36px 8px", ...st }}>
      <div style={{ fontSize: 90, fontWeight: 900, color, lineHeight: 1 }}>{value}</div>
      <div style={{ fontSize: 25, fontWeight: 700, letterSpacing: 1, color: C.dim, marginTop: 16, textTransform: "uppercase" }}>{label}</div>
    </div>
  );
};
const S_Stats: React.FC = () => {
  const f = useCurrentFrame();
  const acc = Math.round(interpolate(f, [9, 39], [0, Math.round(analysis.whiteAccuracy)], clamp));
  const bl = Math.round(interpolate(f, [9, 39], [0, analysis.whiteBlunders], clamp));
  const mis = Math.round(interpolate(f, [9, 39], [0, analysis.whiteMistakes], clamp));
  return (
    <>
      <CapTop>The damage report:</CapTop>
      <div style={{ display: "flex", gap: 22, width: 900, justifyContent: "center" }}>
        <Stat value={`${acc}%`} label="accuracy" color={C.red} delay={3} />
        <Stat value={`${bl}`} label="blunders" color={C.red} delay={9} />
        <Stat value={`${mis}`} label="mistakes" color={C.amber} delay={15} />
      </div>
      <FadeUp delay={40} style={{ marginTop: 36, fontSize: 40, fontWeight: 600, color: "#cbd5e1", lineHeight: 1.4 }}>The fatal move:<br /><b style={{ color: "#fff" }}>c3 — a {(analysis.moves[16].cpLoss / 100).toFixed(1)}-pawn blunder that hung the queen.</b></FadeUp>
    </>
  );
};

const S_Hook2: React.FC = () => (
  <Hooked delay={6} size={84}>And it was<br /><span style={hl}>avoidable</span><br />the whole time.</Hooked>
);
const S_You: React.FC = () => {
  const f = useCurrentFrame();
  const caret = f % 30 < 15 ? 1 : 0;
  return (
    <>
      <Hooked delay={2} size={80}>FireChess finds<br />the leaks in <span style={hl}>your</span><br />games.</Hooked>
      <FadeUp delay={16} style={{ marginTop: 36, fontSize: 56, fontWeight: 800, color: C.green, background: "rgba(16,185,129,.1)", border: "2px solid rgba(16,185,129,.3)", padding: "20px 38px", borderRadius: 18, fontFamily: "ui-monospace, monospace" }}>@yourname<span style={{ opacity: caret }}>▍</span></FadeUp>
    </>
  );
};
const S_End: React.FC = () => (
  <>
    <Hooked delay={2} size={96}><span style={{ color: C.amber, textShadow: "0 0 50px rgba(251,191,36,.5)" }}>🔥 FireChess</span></Hooked>
    <FadeUp delay={12} style={{ marginTop: 18, fontSize: 56, fontWeight: 800 }}>Scan your games free</FadeUp>
    <FadeUp delay={20} style={{ marginTop: 12, fontSize: 36, color: C.dim, fontWeight: 600 }}>No signup. Just search <b style={{ color: "#fff" }}>FireChess</b>.</FadeUp>
  </>
);

// ---------------- root ----------------
type SceneDef = { Comp: React.FC; dur: number; audio: string };
const SCENES: SceneDef[] = [
  { Comp: S_Hook, dur: 204, audio: "hook" },
  { Comp: S_Game, dur: 272, audio: "game" },
  { Comp: S_Fork, dur: 314, audio: "blunder" },
  { Comp: S_Roast, dur: 218, audio: "roast" },
  { Comp: S_Stats, dur: 246, audio: "stats" },
  { Comp: S_Hook2, dur: 130, audio: "hook2" },
  { Comp: S_You, dur: 108, audio: "you" },
  { Comp: S_End, dur: 106, audio: "end" },
];
export const TOTAL_FRAMES = SCENES.reduce((a, s) => a + s.dur, 0);

export const Roast: React.FC = () => {
  const frame = useCurrentFrame();
  const pct = interpolate(frame, [0, TOTAL_FRAMES], [0, 100]);
  let from = 0;
  return (
    <AbsoluteFill style={{ background: "radial-gradient(120% 70% at 50% 16%, #1a0f33 0%, #0a0612 58%, #070410 100%)", color: "#fff", fontFamily }}>
      <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: 8, background: "rgba(255,255,255,.08)", zIndex: 9 }}>
        <div style={{ height: "100%", width: `${pct}%`, background: "linear-gradient(90deg,#a855f7,#f59e0b)" }} />
      </div>
      {frame > 204 && <div style={{ position: "absolute", top: 28, right: 36, fontSize: 28, fontWeight: 800, color: C.amber, opacity: 0.55, zIndex: 9 }}>🔥 FireChess</div>}
      {SCENES.map((s, i) => {
        const el = (
          <Sequence key={i} from={from} durationInFrames={s.dur}>
            <Audio src={staticFile(`vo-${s.audio}.wav`)} />
            <FadeScene dur={s.dur}><s.Comp /></FadeScene>
          </Sequence>
        );
        from += s.dur;
        return el;
      })}
    </AbsoluteFill>
  );
};
