import React from 'react';
import {AbsoluteFill,Audio,Img,interpolate,staticFile,useCurrentFrame,spring} from 'remotion';
import replay from '../public/showcase/replay.json';

const C={bg:'#111b2c',cream:'#fff0cf',lime:'#d9f97a',muted:'#adc1cf',purple:'#bba1ff'};
const clamp={extrapolateLeft:'clamp',extrapolateRight:'clamp'} as const;
const asset=(name:string)=>staticFile(`showcase/${name}`);
const xy=(s:string)=>[s.charCodeAt(0)-97,8-Number(s[1])];
function parse(fen:string){const b:Record<string,string>={};fen.split(' ')[0].split('/').forEach((row,y)=>{let x=0;for(const c of row){if(/\d/.test(c))x+=Number(c);else{b[String.fromCharCode(97+x)+(8-y)]=c;x++;}}});return b;}
// Cosmetic identities reconstructed from this replay's observed extended moves.
// Black's b8 knight becomes the Camel at c6; White's b1 knight becomes the Knook.
function tracked(id:string,start:string,color:'white'|'black'){
 let active=false,sq:string|null=null;
 return replay.frames.map(f=>{
  if(active){if(f.to===sq&&f.from!==sq)sq=null;else if(f.from===sq)sq=f.to;}
  if(!active&&f.state[color].includes(id)){active=true;sq=start;}
  return sq;
 });
}
const camel=tracked('camel','c6','black'),knook=tracked('knook','b1','white');
function code(c:string,square:string,index:number){let p=c.toUpperCase();const color=c===p?'w':'b',mods=replay.frames[index].state[color==='w'?'white':'black'];
 if(p==='N'&&color==='b'&&square===camel[index])p='Ca';
 if(p==='N'&&color==='w'&&square===knook[index])p='C';
 if(p==='R'&&mods.includes('dragon-rook'))p='Dr';
 if(p==='P'&&mods.includes('pawn-capture-forward'))p='PB';
 return color+p;
}
export function ReplayBoard({index,local,size=780,moveAt=25,guide=false,black=false}:{index:number;local:number;size?:number;moveAt?:number;guide?:boolean;black?:boolean}){
 const next=replay.frames[index],prev=replay.frames[index-1],before=parse(prev.fen),after=parse(next.fen),from=next.from!,to=next.to!;
 const t=interpolate(local,[moveAt,moveAt+16],[0,1],clamp),land=t>=1,b=land?after:before,unit=size/8;
 const coord=(square:string)=>{const [x,y]=xy(square);return black?[7-x,7-y]:[x,y];};
 const [fx,fy]=coord(from),[tx,ty]=coord(to),mover=before[from];
 const draw=(s:string,c:string,x:number,y:number,opacity=1,moving=false)=><Img key={moving?'moving':s} src={staticFile(`gameplay/pieces/${code(c,moving?from:s,land?index:index-1)}.svg`)} style={{position:'absolute',left:x*unit,top:y*unit,width:unit,height:unit,opacity,filter:'drop-shadow(0 5px 2px #0005)',zIndex:moving?4:2}}/>;
 return <div style={{width:size+24,height:size+24,padding:12,borderRadius:23,background:'linear-gradient(135deg,#eccb8d,#a6814d)',boxShadow:'0 13px 0 #6b5134,0 24px 55px #0006'}}><div style={{width:size,height:size,position:'relative',overflow:'hidden',borderRadius:9}}>
  {Array.from({length:64},(_,i)=><div key={i} style={{position:'absolute',left:i%8*unit,top:Math.floor(i/8)*unit,width:unit,height:unit,background:(i%8+Math.floor(i/8))%2?'#789ca8':'#eee2be'}}/>)}
  {[from,to].map((s,i)=>{const [x,y]=coord(s);return <div key={s} style={{position:'absolute',left:x*unit,top:y*unit,width:unit,height:unit,background:i?'#d9f97a99':'#ffd77988',border:i?'4px solid #edffac':undefined}}/>;})}
  {guide&&<svg style={{position:'absolute',inset:0,width:size,height:size,zIndex:3,pointerEvents:'none'}} viewBox={`0 0 ${size} ${size}`}><polyline points={`${(fx+.5)*unit},${(fy+.5)*unit} ${(tx+.5)*unit},${(fy+.5)*unit} ${(tx+.5)*unit},${(ty+.5)*unit}`} fill="none" stroke={C.purple} strokeWidth={6} strokeDasharray="10 9" opacity={.8}/></svg>}
  {Object.entries(b).filter(([s])=>land||s!==from).map(([s,c])=>{const [x,y]=coord(s);return draw(s,c,x,y,!land&&s===to?1-t:1);})}
  {!land&&draw(from,mover,fx+(tx-fx)*t,fy+(ty-fy)*t,1,true)}
  {land&&local<moveAt+42&&<div style={{position:'absolute',left:tx*unit,top:ty*unit,width:unit,height:unit,border:'5px solid #eaffad',boxShadow:'inset 0 0 25px #deff84',zIndex:5,opacity:interpolate(local,[moveAt+16,moveAt+42],[1,0],clamp)}}/>}
  {Array.from({length:8},(_,i)=><React.Fragment key={i}><span style={{position:'absolute',left:5,top:i*unit+4,fontSize:size*.021,color:'#354f58',zIndex:6}}>{black?i+1:8-i}</span><span style={{position:'absolute',left:i*unit+unit-16,bottom:4,fontSize:size*.021,color:'#354f58',zIndex:6}}>{(black?'hgfedcba':'abcdefgh')[i]}</span></React.Fragment>)}
 </div></div>;
}
function Shell({children,vertical=false}:{children:React.ReactNode;vertical?:boolean}){const f=useCurrentFrame();return <AbsoluteFill style={{background:C.bg,color:C.cream,fontFamily:'Arial',overflow:'hidden'}}><style>{`@font-face{font-family:Impact;src:url('${staticFile('chaos-promo/impact.ttf')}')}*{box-sizing:border-box}`}</style><AbsoluteFill style={{background:'radial-gradient(ellipse at 72% 50%,#44637366,transparent 72%)'}}/><div style={{position:'absolute',inset:-300,opacity:.035,transform:`rotate(-12deg) translateX(${f*.07}px)`,backgroundImage:'linear-gradient(45deg,#defb9c 25%,transparent 25%,transparent 75%,#defb9c 75%),linear-gradient(45deg,#defb9c 25%,transparent 25%,transparent 75%,#defb9c 75%)',backgroundSize:'160px 160px',backgroundPosition:'0 0,80px 80px'}}/><div style={{position:'absolute',top:vertical?185:45,left:70,display:'flex',gap:15,alignItems:'center',fontSize:vertical?25:23,fontWeight:900,letterSpacing:3}}><Img src={staticFile('chaos-promo/logo.svg')} style={{width:42,height:42}}/>CHAOS CHESS</div>{children}</AbsoluteFill>}
function Head({children,size=86}:{children:React.ReactNode;size?:number}){return <div style={{fontFamily:'Impact',fontSize:size,lineHeight:1.04,letterSpacing:1}}>{children}</div>}
function Eyebrow({children}:{children:React.ReactNode}){return <div style={{color:C.purple,fontSize:22,fontWeight:900,letterSpacing:3,marginBottom:25,textTransform:'uppercase'}}>{children}</div>}
function Card({img,name,description,tier='COMMON',width=330,selected=false,local=100}:{img:string;name:string;description:string;tier?:string;width?:number;selected?:boolean;local?:number}){const p=spring({frame:local,fps:30,config:{damping:17,stiffness:140}});return <div style={{width,background:'#26364d',border:`${selected?5:2}px solid ${selected?C.lime:tier==='COMMON'?'#96a8c6':'#bb9bff'}`,borderRadius:25,overflow:'hidden',boxShadow:selected?'0 0 45px #d9f97a33,0 10px 0 #0b1423':'0 10px 0 #0b1423',transform:`translateY(${(1-p)*95}px) scale(${selected?1.025:1})`,opacity:Math.max(0,p)}}><Img src={asset(img)} style={{width:'100%',height:width*.78,objectFit:'cover'}}/><div style={{padding:24}}><div style={{color:selected?C.lime:C.purple,fontSize:17,fontWeight:900,letterSpacing:2}}>{selected?'SELECTED':tier}</div><div style={{fontFamily:'Impact',fontSize:38,marginTop:12}}>{name}</div><div style={{fontSize:24,lineHeight:1.4,color:'#d0dce5',marginTop:13,minHeight:68}}>{description}</div></div></div>}
function CTA({vertical=false}:{vertical?:boolean}){return <AbsoluteFill style={{alignItems:'center',justifyContent:'center',textAlign:'center'}}><Img src={staticFile('chaos-promo/logo.svg')} style={{width:vertical?145:105,height:vertical?145:105,marginBottom:30}}/><Head size={vertical?130:105}>DRAFT YOUR<br/><span style={{color:C.lime}}>ADVANTAGE.</span></Head><div style={{marginTop:35,fontSize:vertical?32:31}}>Bring a friend. Surprise each other.</div><div style={{marginTop:50,padding:'25px 50px',borderRadius:22,background:'#5865f2',boxShadow:'0 8px 0 #333d9f',fontSize:38,fontWeight:900}}>Play on Discord ↗</div><div style={{marginTop:32,fontSize:32,color:C.lime}}>chaos.firechess.com</div></AbsoluteFill>}

export function CamelShort(){const f=useCurrentFrame();return <Shell vertical><Audio src={staticFile('camel-short/narrated-mix.wav')}/>
 {f<120?<><div style={{position:'absolute',left:70,top:290}}><Head size={102}>THAT ROOK<br/><span style={{color:C.lime}}>WASN'T SAFE.</span></Head></div><div style={{position:'absolute',left:76,top:550}}><ReplayBoard index={19} local={f} size={904} moveAt={18} guide/></div><div style={{position:'absolute',top:1535,left:80,right:80,fontSize:30,fontWeight:800,display:'flex',justifyContent:'space-between'}}><span>CAMEL · 3 + 1 LEAP</span><span style={{color:C.lime}}>REAL REPLAY</span></div></>:
 f<255?<><div style={{position:'absolute',left:70,top:310}}><Eyebrow>One knight. More reach.</Eyebrow><Head size={115}>MEET THE<br/><span style={{color:C.lime}}>CAMEL.</span></Head></div><div style={{position:'absolute',top:630,left:245}}><Card img="camel.webp" name="CAMEL" description="Adds a jump: 3 squares one way, 1 sideways." width={590} local={f-120}/></div></>:
 f<420?<><div style={{position:'absolute',left:70,top:325}}><Head size={103}>WHAT WILL<br/><span style={{color:C.lime}}>YOU DRAFT?</span></Head></div><div style={{position:'absolute',left:45,top:720,display:'flex',gap:25}}><Card img="camel.webp" name="CAMEL" description="Longer leaps." width={310} local={f-255}/><Card img="dragon-rook.webp" name="DRAGON ROOK" description="Diagonal steps." width={310} local={f-263}/><Card img="pawn-bayonet.webp" name="PAWN BAYONET" description="Capture forward." width={310} local={f-271}/></div><div style={{position:'absolute',top:1320,left:70,right:70,textAlign:'center',fontSize:36,color:C.lime,fontWeight:800}}>THREE POWERS. ONE CHOICE.</div><div style={{position:'absolute',top:1400,left:70,right:70,textAlign:'center',fontSize:24,color:C.muted}}>Example powers · every match develops differently.</div></>:<CTA vertical/>}
 </Shell>}

function ReplayScene({index,local,title,subtitle,detail,guide=false,black=false}:{index:number;local:number;title:React.ReactNode;subtitle:string;detail:string;guide?:boolean;black?:boolean}){return <><div style={{position:'absolute',left:80,top:220,width:800}}><Eyebrow>{subtitle}</Eyebrow><Head size={88}>{title}</Head><div style={{marginTop:40,fontSize:31,color:C.muted,lineHeight:1.5,maxWidth:710}}>{detail}</div><div style={{marginTop:38,display:'inline-block',border:'1px solid #6c8e9e',borderRadius:16,padding:'14px 20px',fontSize:21,color:C.lime}}>ACTUAL SAVED MATCH · {replay.frames[index].from} → {replay.frames[index].to}</div></div><div style={{position:'absolute',right:83,top:133}}><ReplayBoard index={index} local={local} size={780} moveAt={25} guide={guide} black={black}/></div></>}

export function GameShowcase(){const f=useCurrentFrame();let content:React.ReactNode;
 if(f<150)content=<ReplayScene index={19} local={f} subtitle="One power changes the threat" title={<>THAT'S NOT<br/>A NORMAL<br/><span style={{color:C.lime}}>KNIGHT.</span></>} detail="The Camel adds a 3 + 1 leap. That rook was in range." guide/>;
 else if(f<330)content=<><div style={{position:'absolute',left:80,top:240,width:560}}><Eyebrow>01 / Find your game</Eyebrow><Head size={89}>SMALL PIECES.<br/><span style={{color:C.lime}}>BIG TROUBLE.</span></Head><div style={{marginTop:40,fontSize:31,lineHeight:1.8,color:C.muted}}>Find an opponent.<br/>Challenge a friend.<br/>Practice against AI.</div></div><div style={{position:'absolute',left:720,top:170,width:1110,height:700,overflow:'hidden',borderRadius:28,border:'2px solid #657087',boxShadow:'0 20px 65px #0008'}}><Img src={asset('lobby.jpg')} style={{width:1110,transform:`translateY(${-Math.min(30,(f-150)*.16)}px)`}}/></div></>;
 else if(f<510)content=<><div style={{position:'absolute',left:80,top:145}}><Eyebrow>02 / Choose an opening anomaly</Eyebrow><Head size={73}>SET THE TONE <span style={{color:C.lime}}>FROM MOVE ONE.</span></Head></div><div style={{position:'absolute',left:290,top:330,display:'flex',gap:55}}><Card img="emperor.webp" name="DOMINION" description="Your king gains a two-square reach." tier="OPENING ANOMALY" width={400} local={f-330}/><Card img="chariot.webp" name="UNSTOPPABLE" description="Rooks pass through friendly pieces." tier="OPENING ANOMALY" width={400} local={f-337}/><Card img="fools-king.webp" name="FOOL'S KING" description="Knight leaps while your king isn't in check." tier="OPENING ANOMALY" width={400} local={f-344}/></div><div style={{position:'absolute',bottom:92,width:'100%',textAlign:'center',fontSize:24,color:C.muted}}>Example anomalies · choose one, or play without one.</div></>;
 else if(f<750)content=<><div style={{position:'absolute',left:80,top:145}}><Eyebrow>03 / Draft as you play</Eyebrow><Head size={80}>EVERY FIVE TURNS. <span style={{color:C.lime}}>A NEW DECISION.</span></Head></div><div style={{position:'absolute',left:290,top:335,display:'flex',gap:55}}><Card img="camel.webp" name="CAMEL" description="One knight gains a 3 + 1 leap." width={400} selected={f>613} local={f-510}/><Card img="dragon-rook.webp" name="DRAGON ROOK" description="Rooks also step one square diagonally." width={400} local={f-518}/><Card img="pawn-bayonet.webp" name="PAWN BAYONET" description="Pawns can capture straight ahead." width={400} local={f-526}/></div><div style={{position:'absolute',bottom:92,width:'100%',textAlign:'center',fontSize:26,color:C.lime}}>Example draft · pick one of three · watch your opponent’s powers.</div></>;
 else if(f<1020){const counter=f>=855;content=<ReplayScene index={counter?31:30} local={counter?f-855:f-750} subtitle="04 / Powers still need a plan" title={counter?<>POWERFUL.<br/><span style={{color:C.lime}}>NOT INVINCIBLE.</span></>:<>KNIGHT JUMPS.<br/><span style={{color:C.lime}}>ROOK MOVES.</span></>} detail={counter?'The opponent takes the Knook. New moves create opportunities—and new ways to overreach.':'The Knook goes from d3 to d7 and takes a pawn. Your upgraded pieces still need protection.'}/>;}
 else if(f<1260){const steps=[{at:1020,i:34},{at:1074,i:35},{at:1128,i:36},{at:1182,i:37}],s=[...steps].reverse().find(s=>s.at<=f)!;const mate=f>=1225;content=<ReplayScene index={s.i} local={f-s.at} subtitle="05 / Black to finish · Black’s perspective" title={mate?<>LONGER LEAP.<br/><span style={{color:C.lime}}>GAME OVER.</span></>:<>SPOT THE<br/><span style={{color:C.lime}}>NEXT THREAT.</span></>} detail={mate?'Checkmate: the Camel on g2 also covers d1, White’s last apparent escape.':'Later in the same game: a queen is lost, a bishop develops, and the Camel finds the finish.'} guide={s.i===37} black/>;}
 else if(f<1470)content=<><div style={{position:'absolute',left:80,top:210,width:630}}><Eyebrow>06 / Play at your pace</Eyebrow><Head size={90}>QUICK GAME?<br/><span style={{color:C.lime}}>LONGER THINK?</span></Head><div style={{marginTop:35,fontSize:30,lineHeight:1.5,color:C.muted}}>Choose your clock.<br/>Clocks pause while picking powers.</div><div style={{marginTop:40,fontSize:22,lineHeight:1.5,color:C.muted}}>Rated play: timed matchmaking with<br/>both signed in through Discord and having moved.</div></div><div style={{position:'absolute',left:820,top:250,display:'grid',gridTemplateColumns:'440px 440px',gap:28}}>{[['2+1','2 min + 1 sec / move'],['5+3','5 min + 3 sec / move'],['10+5','10 min + 5 sec / move'],['No rush','No match clock']].map(([a,b],i)=><div key={a} style={{background:i===1?C.lime:'#284357',color:i===1?C.bg:C.cream,borderRadius:25,padding:40,border:'2px solid #668da0',boxShadow:'0 9px 0 #0c1423'}}><Head size={70}>{a}</Head><div style={{fontSize:24,marginTop:15}}>{b}</div></div>)}</div></>;
 else if(f<1650)content=<><div style={{position:'absolute',left:80,top:230,width:700}}><Eyebrow>07 / Stay for the next game</Eyebrow><Head size={88}>WATCH.<br/>LEARN.<br/><span style={{color:C.lime}}>RUN IT BACK.</span></Head><div style={{display:'flex',gap:15,flexWrap:'wrap',marginTop:45}}>{['Leaderboard','Watch live','Replays'].map(s=><div key={s} style={{padding:'17px 23px',background:'#2e415b',border:'1px solid #71869f',borderRadius:18,fontSize:26}}>{s}</div>)}</div></div><div style={{position:'absolute',left:935,top:145,width:850,height:780,overflow:'hidden',borderRadius:28,border:'2px solid #667f95'}}><Img src={asset('replay-ui.jpg')} style={{position:'absolute',width:1185,left:-197,top:-10-(f-1470)*.34}}/></div></>;
 else content=<CTA/>;
 const chapters=['THE HOOK','FIND A GAME','ANOMALIES','DRAFT POWERS','TACTICS','CHECKMATE','TIME CONTROLS','WATCH & REPLAY','YOUR MOVE'];const ch=f<150?0:f<330?1:f<510?2:f<750?3:f<1020?4:f<1260?5:f<1470?6:f<1650?7:8;
 return <Shell><Audio src={asset('narrated-mix.wav')}/><div style={{position:'absolute',right:80,top:57,fontSize:20,fontWeight:900,color:C.muted,letterSpacing:3}}>THE GAME IN 60 SECONDS</div>{content}<div style={{position:'absolute',left:80,right:80,bottom:38,display:'flex',gap:12,alignItems:'center'}}>{chapters.map((s,i)=><div key={s} style={{height:4,flex:1,background:i<=ch?C.lime:'#ffffff25'}}/>)}<span style={{fontSize:17,color:C.muted,marginLeft:15,minWidth:160,textAlign:'right'}}>{chapters[ch]}</span></div></Shell>;
}
