const ts=require('typescript'),fs=require('fs');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpile(fs.readFileSync(f,'utf8'),{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}),f);
const {test}=require('node:test'),assert=require('node:assert/strict'),{Chess}=require('chess.js');
const {visualState,archiveFrames}=require('../lib/chaos-watch.ts');
const {createSyncState,startServerOpening,metadata,cleanState,reduceCommand}=require('../lib/chaos-room-sync.ts');
let seq=0;function act(r,user,message){return {...r,...reduceCommand(r,user,{id:`watch-test-${++seq}`.padEnd(24,'0'),baseRevision:metadata(r).stateRevision,message},2000+seq*100)}}
function fresh(){let r={id:'watch-test',hostId:'host',guestId:'guest',hostColor:'white',fen:new Chess().fen(),chaosState:createSyncState(true),status:'playing',moveHistory:[],timeControlSeconds:-1};r.chaosState=startServerOpening(r,1000);r=act(r,'host',{type:'anomaly_pick',anomalyId:null});return act(r,'guest',{type:'anomaly_pick',anomalyId:null});}
test('public visual projection excludes chat, authentication, codes and draft offers',()=>{const s=visualState({...createSyncState(true),secret:'hidden',roomCode:'ABCDEF',hostId:'private',_sync:{chat:[{text:'secret'}],opening:{offers:{host:['amazon']}}}});assert.ok(!JSON.stringify(s).includes('secret'));assert.deepEqual(s.white,[]);assert.ok(!('_sync' in s));});
test('replay records authoritative moves and power changes without adding chat or duplicate frames',()=>{let r=fresh();r.fen=r.fen.replace('0 1','0 5');const g=new Chess(r.fen);g.move('e4');r=act(r,'host',{type:'move',fen:g.fen(),lastMoveFrom:'e2',lastMoveTo:'e4',chaosState:cleanState(r.chaosState)});let frames=metadata(r).replayFrames;assert.equal(frames.at(-1).fen,g.fen());assert.equal(frames.at(-1).from,'e2');const before=frames.length;r=act(r,'host',{type:'chat',text:'private'});assert.equal(metadata(r).replayFrames.length,before);const d=metadata(r).draft;r=act(r,'host',{type:'power_pick',draftId:d.id,modifierId:d.choices[0]});frames=metadata(r).replayFrames;assert.equal(frames.length,before+1);assert.ok(frames.at(-1).state.white.includes(d.choices[0]));assert.ok(!JSON.stringify(frames).includes('private'));assert.equal(frames.at(-2).state.white.length,0);assert.equal(archiveFrames({frames})[0].label,'Starting position');});
test('rematches reset replay timeline while the completed timeline stays in the archived game',()=>{let r=fresh();r=act(r,'host',{type:'resign'});const old=metadata(r).replayFrames;r=act(r,'host',{type:'rematch'});r=act(r,'guest',{type:'rematch'});assert.equal(metadata(r).replayFrames.length,1);assert.equal(metadata(r).replayFrames[0].fen,new Chess().fen());assert.ok(old.length>1);});
test('legacy replays use recorded FENs for chaos moves instead of ordinary chess reconstruction',()=>{const fen='4k3/8/8/3B4/8/8/8/4K3 b - - 0 1';const f=archiveFrames({moves:[{from:'c3',to:'d5',fen,powers:{white:['archbishop'],black:[]}}],fen,state:{playerModifiers:[{id:'archbishop'}]}});assert.equal(f[0].fen,fen);assert.deepEqual(f[0].state.white,['archbishop']);assert.equal(f.at(-1).label,'Final position');});
test('spectators cannot submit a move or chat',()=>{const r=fresh();assert.throws(()=>act(r,'spectator',{type:'chat',text:'hello'}));assert.throws(()=>act(r,'spectator',{type:'resign'}));});
