const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const source=ts.transpile(fs.readFileSync('app/api/chaos/discord-token/route.ts','utf8'),{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022});
function route(responses){const writes=[],requests=[];const module={exports:{}};
vm.runInNewContext(source,{module,exports:module.exports,URLSearchParams,AbortSignal,process:{env:{CHAOS_DISCORD_CLIENT_ID:'app',CHAOS_DISCORD_CLIENT_SECRET:'secret'}},
require:name=>name==='next/server'?{NextResponse:{json:(data,options={})=>({data,status:options.status??200})}}:name==='@/lib/db'?{db:{execute:async q=>writes.push(q)}}:name==='drizzle-orm'?{sql:(parts,...values)=>values}:{signDiscordIdentity:id=>'signed:'+id},
fetch:async(url,opts)=>{requests.push({url,opts});return responses.shift();}});return{post:body=>module.exports.POST({text:async()=>JSON.stringify(body)}),writes,requests};}
test('OAuth identity comes from Discord, never a submitted user ID or name',async()=>{const r=route([{ok:true,json:async()=>({access_token:'access'})},{ok:true,json:async()=>({id:'123456789012345678',global_name:'Verified player'})}]);const response=await r.post({code:'code',id:'attacker',name:'forged'});assert.equal(response.status,200);assert.equal(response.data.player.id,'discord_123456789012345678');assert.equal(response.data.player.name,'Verified player');assert.equal(r.writes.length,1);assert.equal(r.requests[1].opts.headers.Authorization,'Bearer access');});
test('rejected OAuth codes cannot create player profiles',async()=>{const r=route([{ok:false}]);assert.equal((await r.post({code:'expired'})).status,401);assert.equal(r.writes.length,0);});
test('invalid code and failed Discord identity lookup fail closed',async()=>{const r=route([]);assert.equal((await r.post({code:{}})).status,400);assert.equal(r.requests.length,0);const unavailable=route([{ok:true,json:async()=>({access_token:'access'})},{ok:false}]);assert.equal((await unavailable.post({code:'code'})).status,503);assert.equal(unavailable.writes.length,0);});
